School-of-Company/Bitgouel-iOS

- App/Sources/Feature/StudentSignUpFeature/StudentSignUpView.swift
- App/Sources/Feature/StudentSignUpFeature/StudentSignUpViewModel.swift
- App/Sources/Feature/StudentSignUpFeature/View/SchoolListRowView.swift
- App/Sources/Feature/StudentSignUpFeature/View/SchoolListView.swift
학생회원가입 검증 로직 리팩토링
- 인증번호 관련 부분을 삭제했습니다
- 학생회원가입 검증 로직을 리팩토링했습니다
> 🔀 :: [#79] 학생회원가입 검증 로직 리팩토링

- App/Resources/Icon/Icons.xcassets/Image.imageset/Contents.json
- App/Resources/Icon/Icons.xcassets/Image.imageset/Frame 7407.svg
- App/Resources/Icon/Icons.xcassets/vertical_ellipsis_fill.imageset/Contents.json
- App/Resources/Icon/Icons.xcassets/vertical_ellipsis_fill.imageset/Frame 7407.svg
- App/Sources/Feature/PostListFeature/Sources/Component/PostListRow.swift
- App/Sources/Feature/PostListFeature/Sources/PostListView.swift
게시글 목록 페이지 퍼블리싱
게시글 목록 페이지를 퍼블리싱했어요
기능 추가하면서 어드민, 학생에 따라 달라지는 Icon 등을 수정할게요.
> 🔀 :: [#129] 게시글 - 게시글 목록 페이지 퍼블리싱

- App/Sources/Application/DI/Post/AppComponent+Post.swift
- App/Sources/Application/NeedleGenerated.swift
- App/Sources/DesignSystem/View/DetailView.swift
- App/Sources/Feature/InputPostFeature/Source/InputPostView.swift
- App/Sources/Feature/PostDetailFeature/Source/PostDetailComponent.swift
- App/Sources/Feature/PostDetailFeature/Source/PostDetailView.swift
- App/Sources/Feature/PostDetailFeature/Source/PostDetailViewModel.swift
- App/Sources/Feature/PostListFeature/Sources/PostListView.swift
- App/Sources/Feature/PostListFeature/Sources/PostListViewModel.swift
- Service/Sources/Domain/PostDomain/API/PostAPI.swift
게시글 상세보기 페이지에 API를 연결했어요.
- queryPostDetailUseCase를 사용해 게시글 상세데이터를 가져왔어요.
- deletePostUseCase를 사용해 게시글 삭제하는 기능을 추가했어요.
- refreshable로 목록을 다시 불러오는 기능을 추가했어요.
DetailView에서 Link를 가져오는 부분에서 오류가 있어서 해결했어요.
PostListView에서 BottomSheet가 필요하지 않게 되어서 삭제했어요.
> 🔀 :: 게시글 - 게시글 상세보기 페이지 API 연결

- .github/workflows/bitgouel-ios-ci.yml
verbose 옵션으로 인해 상세하게나오지만 오히려 Test 실패시 이유를 찾지 못하게 됩니다.
verbose 옵션을 삭제 하였습니다.
> CI 스크립트 verbose 삭제

- App/Sources/Application/DI/AppComponent.swift
- App/Sources/Application/NeedleGenerated.swift
- App/Sources/Feature/InputNoticeFeature/Source/InputNoticeComponent.swift
- App/Sources/Feature/InputNoticeFeature/Source/InputNoticeView.swift
- App/Sources/Feature/InputNoticeFeature/Source/InputNoticeViewModel.swift
- App/Sources/Feature/NoticeDetailSettingFeature/Interface/NoticeDetailSettingFactory.swift
- App/Sources/Feature/NoticeDetailSettingFeature/Source/NoticeDetailSettingComponent.swift
- App/Sources/Feature/NoticeDetailSettingFeature/Source/NoticeDetailSettingView.swift
- App/Sources/Feature/NoticeDetailSettingFeature/Source/NoticeDetailSettingViewModel.swift
- App/Sources/Feature/NoticeListFeature/Source/NoticeListComponent.swift
- App/Sources/Feature/NoticeListFeature/Source/NoticeListView.swift
- App/Sources/Feature/NoticeListFeature/Source/NoticeListViewModel.swift
공지사항 세부설정 페이지를 추가했어요.
https://github.com/GSM-MSG/Bitgouel-iOS/assets/105629604/db696dd0-c22f-4469-8c15-87211e4088f9
NoticeListView에서 admin만 공지사항을 추가할 수 있도록 변경했어요.
> 🔀 :: [#197] 공지사항 - 공지사항 세부설정 페이지 추가

- App/Sources/Feature/ActivityDetailFeature/Sources/ActivityDetailView.swift
- App/Sources/Feature/ActivityDetailFeature/Sources/ActivityDetailViewModel.swift
- App/Sources/Feature/ActivityDetailSettingFeature/Sources/ActivityDetailSettingView.swift
- App/Sources/Feature/InputActivityFeature/Source/InputActivityViewModel.swift
- Service/Sources/Domain/ActivityDomain/DTO/Response/ActivityDetailResponseDTO.swift
- Service/Sources/Domain/ActivityDomain/Entity/ActivityDetailEntity.swift
- Service/Sources/Testing/UseCase/FetchActivityDetailUseCaseStub.swift
학생활동 상세보기 페이지를 리팩토링했어요.
디자인이랑 현재 코드랑 다른 부분이 있어서 수정했어요.
ActivityDetailEntity에 있는 activityDate의 Type을 Date로 변경해서 2024-03-04 처럼 보여져서 디자인과 다르던 활동날짜를 2024.3.4로 보여지도록 변경했어요.
> 🔀 :: [#225] 학생활동 상세보기 페이지 리팩토링

- App/Sources/Application/NeedleGenerated.swift
- App/Sources/Feature/ActivityDetailFeature/Sources/ActivityDetailView.swift
- App/Sources/Feature/CertificationListFeature/Source/CertificationListView.swift
- App/Sources/Feature/CertificationListFeature/Source/CertificationListViewModel.swift
- App/Sources/Feature/InputCertificationFeature/Interface/InputCertificationFactory.swift
- App/Sources/Feature/InputCertificationFeature/Source/InputCertificationComponent.swift
- App/Sources/Feature/InputCertificationFeature/Source/InputCertificationViewModel.swift
깜빡하고 추가 안 한 자격증 수정 페이지 이동을 추가했어요.
https://github.com/GSM-MSG/Bitgouel-iOS/assets/105629604/bd0fadf6-f2a5-4644-8836-bbb20b2e4268
자격증 리스트 Row에서 수정 버튼을 누르면 수정 페이지 모달이 뜨게 추가했어요.
수정 페이지에 필요한 certificationName, acquisitionDate, certificationID를 리스트 페이지에서 보내도록 변경했어요.
> 🔀 :: [#235] 자격증 수정 버튼 클릭 시 페이지 이동 추가

- App/Sources/Application/NeedleGenerated.swift
- App/Sources/Feature/AdminUserListFeature/Source/AdminUserListComponent.swift
- App/Sources/Feature/AdminUserListFeature/Source/AdminUserListView.swift
- App/Sources/Feature/AdminUserListFeature/Source/AdminUserListViewModel.swift
- App/Sources/Feature/MyPageFeature/Source/MyPageComponent.swift
- App/Sources/Feature/MyPageFeature/Source/MyPageView.swift
- App/Sources/Feature/MyPageFeature/Source/MyPageViewModel.swift
사용자 명단 페이지 API 연결
어드민 사용자 명단페이지에 사용자 명단을 조회하는 기능을 추가했어요.
어드민일 때 사용자 명단 관리하기 Button 클릭 시 페이지로 이동하는 Action을 추가했어요.
selectedAuthority가 nil일 때 빈 문자열로 요청을 보내야 해서 Optional값으로 변경했어요.
viewModel에 선언되어있던 Factory를 삭제 했어요.
> 🔀 :: [#246] 어드민 - 사용자 명단 페이지 API 연결

- App/Sources/Application/NeedleGenerated.swift
- App/Sources/Feature/AdminRequestUserSignupFeature/Source/AdminRequestUserSignupComponent.swift
- App/Sources/Feature/AdminRequestUserSignupFeature/Source/AdminRequestUserSignupView.swift
- App/Sources/Feature/AdminRequestUserSignupFeature/Source/AdminRequestUserSignupViewModel.swift
- App/Sources/Feature/AdminUserListFeature/Source/AdminUserListView.swift
- Service/Sources/Data/DataSource/Admin/RemoteAdminDataSourceImpl.swift
- Service/Sources/Data/Repository/Admin/AdminRespositoryImpl.swift
- Service/Sources/Data/UseCase/Admin/ApproveUserSignupUseCaseImpl.swift
- Service/Sources/Data/UseCase/Admin/RejectUserSignupUseCaseImpl.swift
- Service/Sources/Data/UseCase/Admin/WithdrawUserUseCaseImpl.swift
- Service/Sources/Domain/AdminDomain/API/AdminAPI.swift
- Service/Sources/Domain/AdminDomain/DataSource/RemoteAdminDataSource.swift
- Service/Sources/Domain/AdminDomain/Repository/AdminRepository.swift
- Service/Sources/Domain/AdminDomain/UseCase/ApproveUserSignupUseCase.swift
- Service/Sources/Domain/AdminDomain/UseCase/RejectUserSignupUseCase.swift
- Service/Sources/Domain/AdminDomain/UseCase/WithdrawUserSignupUseCase.swift
가입 요청자 명단 페이지 API 연결
가입 요청자 명단 리스트를 조회하는 기능을 추가했어요.
유저 선택, 전체 선택 기능을 추가했어요.
유저 가입요청 수락 기능을 추가했어요.
유저 가입요청 거절 기능을 추가했어요.
userID를 보낼 때 잘 못된 부분이 있어서 수정했어요.
> 🔀 :: [#246] 어드민 - 가입 요청자 명단 페이지 API 연결

- App/Sources/Application/NeedleGenerated.swift
- App/Sources/Feature/AdminWithdrawUserListFeature/Source/AdminWithdrawUserListComponent.swift
- App/Sources/Feature/AdminWithdrawUserListFeature/Source/AdminWithdrawUserListView.swift
- App/Sources/Feature/AdminWithdrawUserListFeature/Source/AdminWithdrawUserListViewModel.swift
- App/Sources/Feature/AdminWithdrawUserListFeature/Source/Component/UserCohortFilterPopup.swift
- Service/Sources/Domain/AdminDomain/API/AdminAPI.swift
- Service/Sources/Domain/WithdrawDomain/DTO/Response/FetchWithdrawUserListResponseDTO.swift
- Service/Sources/Domain/WithdrawDomain/Entity/WithdrawUserInfoEntity.swift
어드민 - 탈퇴 예정자 명단 페이지 API 연결
탈퇴 예정자 조회 기능을 추가했어요.
유저 강제 탈퇴 기능 추가했어요.
navigationTitle이 사용자 명단에서 탈퇴 예정자 명단으로 변경했어요.
withdrawID의 Type을 String에서 Int로 변경했어요.
> 🔀 :: [#246] 어드민 - 탈퇴 예정자 명단 페이지 API 연결

- App/Sources/Application/DI/AppComponent.swift
- App/Sources/Application/DI/Email/AppComponent+Email.swift
- App/Sources/Application/NeedleGenerated.swift
- App/Sources/Feature/BaseFeature/Flow/SceneFlow.swift
- App/Sources/Feature/FindPasswordFeature/Source/FindPasswordComponent.swift
- App/Sources/Feature/FindPasswordFeature/Source/FindPasswordView.swift
- App/Sources/Feature/FindPasswordFeature/Source/FindPasswordViewModel.swift
- App/Sources/Feature/FindPasswordFeature/Source/View/SendEmailView.swift
- App/Sources/Feature/LoginFeature/Sources/LoginView.swift
- App/Sources/Feature/NewPasswordFeature/Interface/NewPasswordFactory.swift
- App/Sources/Feature/NewPasswordFeature/Source/NewPasswordComponent.swift
- App/Sources/Feature/NewPasswordFeature/Source/NewPasswordView.swift
- App/Sources/Feature/NewPasswordFeature/Source/NewPasswordViewModel.swift
- App/Sources/Feature/NewPasswordFeature/Source/View/SuccessFindPasswordView.swift
- App/Sources/Feature/RootFeature/RootComponent.swift
- App/Sources/Feature/RootFeature/RootView.swift
- Service/Sources/Data/DataSource/Email/RemoteEmailDataSourceImpl.swift
- Service/Sources/Data/Repository/Email/EmailRepositoryImpl.swift
- Service/Sources/Data/UseCase/Email/FetchEmailVerificationStatusUseCaseImpl.swift
- Service/Sources/Domain/EmailDomain/DTO/FetchEmailVerificationStatusResponseDTO.swift
- Service/Sources/Domain/EmailDomain/DataSource/RemoteEmailDataSource.swift
- Service/Sources/Domain/EmailDomain/Entity/EmailVerificationStatusEntity.swift
- Service/Sources/Domain/EmailDomain/Repository/EmailRepository.swift
- Service/Sources/Domain/EmailDomain/UseCase/FetchEmailVertificationStatusUseCase.swift
비밀번호 찾기 - 이메일 인증 시 비밀번호 변경 페이지를 퍼블리싱 했어요.
https://github.com/GSM-MSG/Bitgouel-iOS/assets/105629604/1697af89-d1c9-4d1e-b554-a249a0af4263
fetchEmailVerificationStatus의 return 값을 EmailVerificationStatusEntity에서 Bool로 변경했어요.
다음으로 버튼에 .disabled(viewModel.isPasswordEmpty)을 추가하여 이메일, 비밀번호를 입력했을 시에만 클릭 가능하도록 변경했어요.
> 🔀 :: [#252] 비밀번호 찾기 - 비밀번호 변경 페이지 퍼블리싱

- App/Sources/Application/NeedleGenerated.swift
- App/Sources/Feature/MainFeature/Source/MainComponent.swift
- App/Sources/Feature/MainFeature/Source/MainView.swift
- App/Sources/Feature/MainFeature/Source/MainViewModel.swift
- App/Sources/Feature/MainFeature/Source/View/FAQView.swift
- App/Sources/Feature/MainFeature/Source/View/InputFAQView.swift
- Service/Sources/Domain/FAQDomain/DTO/Response/FetchFAQListResponseDTO.swift
- Service/Sources/Domain/FAQDomain/Entity/FAQInfoEntity.swift
메인페이지에 FAQ부분에 API를 연결했어요.
FAQ리스트 조회 기능을 추가했어요.
자주 묻는 질문을 추가하는 기능을 추가했어요.
자주 묻는 질문을 추가하는 버튼, 추가 Row를 제작했어요.
fetchFAQListResponseDTO에 response값이 faqList에서 faqs로 변경되었어요.
FAQInfoEntity에 questionID가 String에서 Int로 타입이 변환되었어요.
> 🔀 :: [#262] 메인페이지 - FAQ API 연결

- App/Sources/Feature/FindPasswordFeature/Source/FindPasswordView.swift
비밀번호 찾기 페이지로 이동 후 돌아가기 버튼을 누르면 로그인 페이지로 이동하지 않던 문제가 있었어요.
backButton에 dismiss Action을 추가해줬어요.
화면 선택시 키보드가 사라지도록 수정했어요.
> 🔀 :: [#270] dismiss Action 추가

- App/Sources/Feature/AdminRequestUserSignupFeature/Source/AdminRequestUserSignupView.swift
- App/Sources/Feature/AdminWithdrawUserListFeature/Source/AdminWithdrawUserListView.swift
탈퇴예정자명단 페이지에 있는 필터 버튼, 가입요청자명단 페이지에 있는 전체 선택 버튼의 Text가 두 줄로 나오는 문제가 있었어요.
디자인보다 horizontal, vertical padding이 더 많이 들어가 있어서 알맞게 수정했어요.
> 🔀 :: [#272] ButtonPadding 수정

- App/Sources/Feature/ChangePasswordFeature/Source/ChangePasswordView.swift
- App/Sources/Feature/LoginFeature/Sources/LoginView.swift
비밀번호 변경, 로그인 페이지에 화면 선택 시 키보드가 내려가지 않던 문제가 있었어요.
hideKeyboard를 추가해서 해결했어요.
> 🔀 :: [#274] hideKeyboard 추가

- App/Sources/Feature/LectureListDetailFeature/LectureListDetailView.swift
- App/Sources/Feature/LectureListDetailFeature/LectureListDetailViewModel.swift
수강신청 요청실패 시 어떠한 메시지도 없이 실패하고 아무일도 일어나지 않는 현상이 발견되었어요.
Resolves: #287 
- 강의 수강신청 실패시 에러메세지를 Toast로 띄우도록 추가했어요.
- 강의 상세정보 요청시 딜레이를 ProgressView를 사용했어요.
> 🔀 :: [#287] 강의 수강신청 실패 에러처리

- App/Sources/Application/DI/Lecture/AppComponent+Lecture.swift
- App/Sources/Application/NeedleGenerated.swift
- App/Sources/Feature/LectureApplicantListFeature/Source/Component/LectureApplicantListRow.swift
- App/Sources/Feature/LectureApplicantListFeature/Source/LectureApplicantListComponent.swift
- App/Sources/Feature/LectureApplicantListFeature/Source/LectureApplicantListView.swift
- App/Sources/Feature/LectureApplicantListFeature/Source/LectureApplicantListViewModel.swift
- App/Sources/Feature/LectureListDetailFeature/LectureListDetailView.swift
- Service/Sources/Data/DataSource/Lecture/RemoteLectureDataSourceImpl.swift
- Service/Sources/Data/Repository/Lecture/LectureRepositoryImpl.swift
- Service/Sources/Data/UseCase/Lecture/FetchApplicantListUseCaseImpl.swift
- Service/Sources/Data/UseCase/Lecture/ModifyApplicantWhetherUseCaseImpl.swift
- Service/Sources/Domain/LectureDomain/API/LectureAPI.swift
- Service/Sources/Domain/LectureDomain/DTO/Response/FetchApplicantListResponseDTO.swift
- Service/Sources/Domain/LectureDomain/DataSource/RemoteLectureDataSource.swift
- Service/Sources/Domain/LectureDomain/Entity/ApplicantInfoEntity.swift
- Service/Sources/Domain/LectureDomain/Repository/LectureRepository.swift
- Service/Sources/Domain/LectureDomain/UseCase/FetchApplicantListUseCase.swift
- Service/Sources/Domain/LectureDomain/UseCase/ModifyApplicantWhetherUseCase.swift
강의 이수 중인 학생 전체 조회, 강의 이수 여부 수정 기능 추가
Resolves: #291 
- 강의 이수 중인 학생 전체 조회, 강의 이수 여부 수정 기능을 추가 했어요.
- 강의 이수 중인 학생 조회 기능 권한을 admin, teacher에서 admin, teacher, professor, companyinstructor, government, bbozzack으로 확대했어요.
> 🔀 :: [#291] 강의 이수 중인 학생 전체 조회, 강의 이수 여부 수정 기능 추가

- App/Sources/Feature/InquiryDetailFeature/Source/InquiryDetailView.swift
테스트 중 문의사항 상세보기페이지에서 답변되지 않은 문의사항일 때 답변됨 표시가 뜨는 문제가 있었어요.
Resolves: #305 
- 답변되지 않은 문의사항일 때 답변됨 표시가 뜨지 않도록 수정했어요.
- 문의사항을 작성한 시간을 보여주는 Date가 포맷이 잘못되어있어서 수정했어요.
> 🔀 :: [#305] 답변되지 않은 문의사항일 때 답변됨 표시 수정

- App/Sources/Feature/ClubDetailFaeture/Source/ClubDetailView.swift
- App/Sources/Feature/ClubDetailFaeture/Source/ClubDetailViewModel.swift
- App/Sources/Feature/ClubListFeature/Source/ClubListView.swift
- App/Sources/Feature/LectureApplicantListFeature/Source/Component/LectureApplicantListRow.swift
- App/Sources/Feature/StudentInfoFeature/Source/StudentInfoView.swift
- App/Sources/Utils/Extensions/String+withHypen.swift
어드민 제외 유저 역할들은 동아리 탭을 선택했을 때 바로 유저가 소속되어있는 동아리의 상세페이지로 이동하게 되어있어요.
그러나, 동아리 상세페이지의 탭바가 Hidden되어있어서 어드민이 아닌 유저의 페이지 이동이
동아리 상세 -> 백버튼 -> 동아리 목록 -> 탭바 이동으로 되어있어서 이동이 불편했어요.
Resolves: #307 
- 어드민이 아닌 유저들의 동아리 목록 BackButton을 Hidden해서 동아리 목록페이지로 이동할 수 없게 변경했어요.
- 추가로 동아리 상세 페이지에 Tabbar Hidden을 삭제해 탭바 이동을 편하게 할 수 있도록 변경했어요.
- 전화번호 text가 010-0000-0000으로 표현되는 게 아니라 01000000000로 표현되어있어서 하이픈을 추가해주는 String Extensions을 추가했어요.
> 🔀 :: [#307] 동아리 목록 페이지 접근 권한 수정

- App/Sources/DesignSystem/View/NoInfoView.swift
- App/Sources/Feature/ActivityListFeature/Source/ActivityListView.swift
- App/Sources/Feature/AdminRequestUserSignupFeature/Source/AdminRequestUserSignupView.swift
- App/Sources/Feature/AdminWithdrawUserListFeature/Source/AdminWithdrawUserListView.swift
- App/Sources/Feature/InquiryListFeature/Source/InquiryListView.swift
- App/Sources/Feature/LectureDetailSettingFeature/Sources/Component/BottomSheet/InstructorBottomSheet.swift
- App/Sources/Feature/LectureListFeature/Source/LectureListView.swift
- App/Sources/Feature/MainFeature/Source/MainView.swift
- App/Sources/Feature/MainFeature/Source/View/HighSchoolPromotionView.swift
- App/Sources/Feature/NoticeListFeature/Source/NoticeListView.swift
- App/Sources/Feature/PostListFeature/Sources/PostListView.swift
테스트 중 어드민 페이지에서 가입 요청자, 탈퇴 예정자 페이지에 유저가 없을 때 NoInfoView가 보이는 것이 좋을 것 같다고 판단했어요.
Resolves: #308 
- 어드민 - 가입 요청자, 탈퇴 예정자 페이지에 유저가 없을 때 NoInfoView가 띄워지도록 수정했어요.
- NoInfoView에 text를 직접입력하도록 수정해서 원하는 정보가 없다고 정확히 알려줄 수 있도록 변경했어요.
> 🔀 :: [#308] 어드민 - 가입 요청자, 탈퇴 예정자 페이지에 유저가 없을 때 NoInfoView 추가

- App/Sources/Feature/MainFeature/Source/MainViewModel.swift
어드민일 때 메인페이지에 FAQ 추가를 성공해도 FAQ가 추가되지 않는 오류가 있었어요.
Resolves: #313 
- FAQ 추가가 성공했을 때 onAppear함수를 한 번 더 호출하도록 변경했어요.
> 🔀 :: [#313] FAQ추가 성공시 FAQ리스트 재요청

- App/Sources/Feature/LectureListDetailFeature/LectureListDetailView.swift
- App/Sources/Feature/LectureListFeature/Source/Component/LectureListRow.swift
- App/Sources/Feature/LectureListFeature/Source/LectureListView.swift
- App/Sources/Feature/LectureListFeature/Source/LectureListViewModel.swift
- App/Sources/Feature/MainFeature/Source/TabView/Club/AiFusionAndCompositeClubView.swift
- App/Sources/Feature/MainFeature/Source/TabView/Club/CultureIndustryClubView.swift
- App/Sources/Feature/MainFeature/Source/TabView/Club/EnergyIndustryClubView.swift
- App/Sources/Feature/MainFeature/Source/TabView/Club/FutureTransportClubView.swift
- App/Sources/Feature/MainFeature/Source/TabView/Club/MedicalHealthClubView.swift
- App/Sources/Feature/MainFeature/Source/TabView/Company/AiFusionAndCompositeCompanyView.swift
- App/Sources/Feature/MainFeature/Source/TabView/Company/CultureIndustryCompanyView.swift
- App/Sources/Feature/MainFeature/Source/TabView/Company/EnergyIndustryCompanyView.swift
- App/Sources/Feature/MainFeature/Source/TabView/Company/FutureTransportCompanyView.swift
- App/Sources/Feature/MainFeature/Source/TabView/Company/MedicalHealthCompanyView.swift
- Service/Sources/Domain/LectureDomain/DTO/Response/FetchLectureDetailResponseDTO.swift
- Service/Sources/Domain/LectureDomain/DTO/Response/FetchLectureListResponseDTO.swift
- Service/Sources/Domain/LectureDomain/Entity/LectureDetailEntity.swift
- Service/Sources/Domain/LectureDomain/Entity/LectureListEntity.swift
강의 리스트, 상세를 Response하는 과정에서 LectureType이 String으로 오는데 저희가 정해놓은 enum인 LectureType으로 Type을 지정해 두어서 리스트, 상세를 Response 하지 못하는 문제가 있었어요.
Resolves: #319 
- LectureDomain - 강의 리스트, 상세 ResponseDTO, Entity의 LectureType을 String으로 수정했어요.
- 강의 리스트, 상세 보기 페이지에 LectureType을 String으로 변경했어요.
- 메인 페이지에 동아리, 참여기업을 소개하는 부분의 배경 Image가 크기가 큰 시뮬레이터로 빌드 했을 때 잘리는 문제가있어서 해결했어요.
> 🔀 :: [#319] 강의 유형 LectureType -> String으로 수정 

- App/Support/Info.plist
다크모드 디자인이 따로 없고 대응할 방안이 없는 상황에서 QA중 다크모드로 테스트하면서 제대로 UI가 그려지지 않는 문제가 있었어요.
Resolves: #325 
- 다크모드로 접근할 수 없도록 라이트 모드 제한을 추가했습니다.
- 
> 🔀 :: [#325] 다크모드 제한 설정 추가

- Service/Sources/Domain/ActivityDomain/API/ActivityAPI.swift
- Service/Sources/Domain/ActivityDomain/Error/ActivityDomainError.swift
- Service/Sources/Domain/AdminDomain/API/AdminAPI.swift
- Service/Sources/Domain/AdminDomain/Error/AdminDomainError.swift
- Service/Sources/Domain/AuthDomain/API/AuthAPI.swift
- Service/Sources/Domain/AuthDomain/Error/AuthDomainError.swift
- Service/Sources/Domain/CertificationDomain/API/CertificationAPI.swift
- Service/Sources/Domain/CertificationDomain/Error/CertificationDomainError.swift
- Service/Sources/Domain/ClubDomain/API/ClubAPI.swift
- Service/Sources/Domain/ClubDomain/Error/ClubDomainError.swift
- Service/Sources/Domain/EmailDomain/API/EmailAPI.swift
- Service/Sources/Domain/FAQDomain/API/FAQAPI.swift
- Service/Sources/Domain/FAQDomain/Error/FAQDomainError.swift
- Service/Sources/Domain/InquiryDomain/API/InquiryAPI.swift
- Service/Sources/Domain/InquiryDomain/Error/InquiryDomainError.swift
- Service/Sources/Domain/LectureDomain/API/LectureAPI.swift
- Service/Sources/Domain/LectureDomain/Error/LectureDomainError.swift
- Service/Sources/Domain/PostDomain/API/PostAPI.swift
- Service/Sources/Domain/PostDomain/Error/PostDomainError.swift
- Service/Sources/Domain/UserDomain/API/UserAPI.swift
- Service/Sources/Domain/UserDomain/Error/UserDomainError.swift
예외처리를 진행하던 도중 Description이 추가된 Domain이 있고 추가되지 않은 도메인이 있어서 맞추기 위해서 Description을 추가했어요.
Resolves: #329
- Auth, Club, Inquiry, Lecture, post, user Domain의 Error Description을 추가했어요.
- Certification, FAQ, Activity, Admin Domain의 Error Description을 수정했어요.
-
> 🔀 [#329] Domain별 Description 추가

- App/Sources/Feature/ActivityDetailFeature/Sources/ActivityDetailView.swift
- App/Sources/Feature/ActivityDetailFeature/Sources/ActivityDetailViewModel.swift
- App/Sources/Feature/ActivityListFeature/Source/ActivityListView.swift
- App/Sources/Feature/ActivityListFeature/Source/ActivityListViewModel.swift
- App/Sources/Feature/InputActivityFeature/Source/InputActivityView.swift
- App/Sources/Feature/InputActivityFeature/Source/InputActivityViewModel.swift
- App/Sources/Utils/Extensions/Error+DomainErrorMessage.swift
QA진행 중 학생활동 Feature들이 요청이 실패했을 때 예외처리가 진행되지 않아서 불편함을 겪었어요.
Resolves: #329
- 학생활동 목록
- 학생활동 상세
- 학생활동 입력(+수정)
페이지에 요청 실패 시 Toast메시지를 띄우도록 수정했어요!
요청 실패시 catch 부분에 들어가는 코드들이 너무 중복되어서 줄여보려고 일단 각 Domain별로 다른 errorDescription을 띄우기 위해서 extension을 만들어 봤는데 실행은 잘 됩니다!! 읽어보시고 더 개선하면 좋을 점이 있다면 알려주세요!!
> 🔀 :: [#329] 학생활동 예외처리

- App/Sources/Feature/AdminRequestUserSignupFeature/Source/AdminRequestUserSignupView.swift
- App/Sources/Feature/AdminRequestUserSignupFeature/Source/AdminRequestUserSignupViewModel.swift
- App/Sources/Feature/AdminUserListFeature/Source/AdminUserListView.swift
- App/Sources/Feature/AdminUserListFeature/Source/AdminUserListViewModel.swift
- App/Sources/Feature/AdminWithdrawUserListFeature/Source/AdminWithdrawUserListView.swift
- App/Sources/Feature/AdminWithdrawUserListFeature/Source/AdminWithdrawUserListViewModel.swift
QA진행 중 어드민 페이지들의 예외처리가 진행되지 않아 불편함을 느끼는 문제가 있었어요.
- 가입요청자 페이지 - 명단 조회, 유저 가입 수락, 거절
- 탈퇴예정자  페이지 - 명단 조회, 유저 강제 탈퇴 
- 사용자 명단 페이지 - 명단조회 
위의 요청들이 실패했을 때 Toast메시지를 띄우도록 예외처리를 추가했어요.
> 🔀 :: [#329] 어드민 Feature 예외처리

- App/Sources/Feature/ChangePasswordFeature/Source/ChangePasswordView.swift
- App/Sources/Feature/ChangePasswordFeature/Source/ChangePasswordViewModel.swift
- App/Sources/Feature/FindPasswordFeature/Source/FindPasswordView.swift
- App/Sources/Feature/FindPasswordFeature/Source/FindPasswordViewModel.swift
QA진행 중 비밀번호 찾기, 변경 중 요청이 실패했을 때 예외처리가 진행되지 않아 불편함을 느끼는 문제가 발생했어요.
- 비밀번호 찾기, 변경의 요청 실패시 Toast메시지를 띄우도록 추가했어요.
> 🔀 :: [#329] 비밀번호 찾기, 변경 예외처리 추가

- App/Sources/Feature/ClubDetailFaeture/Source/ClubDetailView.swift
- App/Sources/Feature/ClubDetailFaeture/Source/ClubDetailViewModel.swift
- App/Sources/Feature/ClubListFeature/Source/ClubListView.swift
- App/Sources/Feature/ClubListFeature/Source/ClubListViewModel.swift
QA 진행 중 동아리 목록, 상세 조회 시 요청이 실패했을 때 예외처리가 진행되지 않아서 불편함을 겪었어요.
- 동아리 목록 조회
- 동아리 상세 조회
요청이 실패했을 때 Toast메시지를 띄우도록 추가했어요.
> 🔀 :: [#329] 동아리 목록, 상세 예외처리

- App/Sources/Feature/InputInquiryFeature/Source/InputInquiryView.swift
- App/Sources/Feature/InputInquiryFeature/Source/InputInquiryViewModel.swift
- App/Sources/Feature/InquiryDetailFeature/Source/InquiryDetailView.swift
- App/Sources/Feature/InquiryDetailFeature/Source/InquiryDetailViewModel.swift
- App/Sources/Feature/InquiryListFeature/Source/InquiryListView.swift
- App/Sources/Feature/InquiryListFeature/Source/InquiryListViewModel.swift
- App/Sources/Feature/WriteInquiryAnswerFeature/Source/WriteInquiryAnswerView.swift
- App/Sources/Feature/WriteInquiryAnswerFeature/Source/WriteInquiryAnswerViewModel.swift
QA진행 중에 문의사항 조회, 상세 조회, 답변 추가, 삭제, 수정, 작성 요청이 실패했을 때 예외처리가 진행되지 않아 불편함을 느끼는 문제가 발생했어요.
- 문의사항 작성
- 문의사항 리스트 조회
- 문의사항 상세 조회
- 문의사항 삭제, 수정
- 문의사항 답변
위 요청들이 실패했을 때 Toast메시지를 띄우도록 예외처리를 진행했어요.
> 🔀 :: [#329] 문의사항 Feature 예외처리 추가

- App/Sources/Feature/LectureApplicantListFeature/Source/LectureApplicantListView.swift
- App/Sources/Feature/LectureApplicantListFeature/Source/LectureApplicantListViewModel.swift
- App/Sources/Feature/LectureDetailSettingFeature/Sources/LectureDetailSettingViewModel.swift
- App/Sources/Feature/LectureListDetailFeature/LectureListDetailView.swift
- App/Sources/Feature/LectureListDetailFeature/LectureListDetailViewModel.swift
- App/Sources/Feature/LectureListFeature/Source/LectureListView.swift
- App/Sources/Feature/LectureListFeature/Source/LectureListViewModel.swift
- App/Sources/Feature/OpenedLectureFeature/Sources/OpenedLectureView.swift
- App/Sources/Feature/OpenedLectureFeature/Sources/OpenedLectureViewModel.swift
QA진행 중 강의 목록 조회, 강의 상세 조회, 신청자 명단 조회, 개설 요청 실패 시 아무런 조치가 없어서 사용 중 불편함을 느꼈어요.
- 강의 리스트 조회
- 강의 상세정보 조회
- 강의 수강 신청
- 강의 수강 신청 취소
- 강의 이수 중인 학생 전체 조회
- 강의 이수 여부 수정
기능의 요청이 실패 할 때 Toast메시지가 띄워지도록 추가했어요.
> 🔀 :: [#329] 강의 Feature 예외 처리

- App/Sources/Feature/InputNoticeFeature/Source/InputNoticeView.swift
- App/Sources/Feature/InputNoticeFeature/Source/InputNoticeViewModel.swift
- App/Sources/Feature/NoticeDetailFeature/Source/NoticeDetailView.swift
- App/Sources/Feature/NoticeDetailFeature/Source/NoticeDetailViewModel.swift
- App/Sources/Feature/NoticeListFeature/Source/NoticeListView.swift
- App/Sources/Feature/NoticeListFeature/Source/NoticeListViewModel.swift
QA진행 중 공지사항 리스트 조회, 상세 조회, 수정, 삭제, 작성 요청이 실패했을 때의 조치가 취해지지 않아 불편함을 느꼈어요.
- 공지사항 리스트 조회
- 공지사항 상세 조회
- 공지사항 수정, 삭제, 작성
위 요청들이 실패했을 때 Toast메시지가 띄워지도록 추가했어요
> 🔀 :: [#329] 공지사항 Feature 예외 처리

- App/Sources/Application/NeedleGenerated.swift
- App/Sources/Feature/ChangePasswordFeature/Source/ChangePasswordView.swift
- App/Sources/Feature/ChangePasswordFeature/Source/ChangePasswordViewModel.swift
- App/Sources/Feature/FindPasswordFeature/Source/FindPasswordView.swift
- App/Sources/Feature/FindPasswordFeature/Source/FindPasswordViewModel.swift
- App/Sources/Feature/LoginFeature/Sources/LoginView.swift
- App/Sources/Feature/LoginFeature/Sources/LoginViewModel.swift
- App/Sources/Feature/MyPageFeature/Source/MyPageViewModel.swift
- App/Sources/Feature/SignUpFeature/SignUpView.swift
- App/Sources/Feature/SignUpFeature/SignUpViewModel.swift
- App/Sources/Utils/Extensions/Error+DomainErrorMessage.swift
- Service/Sources/Base/DataSource/BaseRemoteDataSource.swift
- Service/Sources/Domain/AuthDomain/Error/AuthDomainError.swift
- Service/Sources/Domain/EmailDomain/API/EmailAPI.swift
- Service/Sources/Domain/EmailDomain/Error/EmailDomainError.swift
- Service/Sources/Domain/UserDomain/API/UserAPI.swift
- Service/Sources/Domain/UserDomain/Error/UserDomainError.swift
QA결과에서 로그인, 비밀번호 찾기, 비밀번호 변경, 회원가입 페이지에서 비밀번호, 이메일, 전화번호의 유효성검사가 진행되지 않고, 발생한 문제들을 알려주지 않고 있어서 불편하다는 문제가 있었어요.
Resolves: #346 
- 로그인 페이지에서 로그인 버튼 클릭시 유효성을 검사하도록 수정했어요.
- 로그인 페이지에서 아직 승인되지 않은 계정으로 가입할 때 리프레시 토큰 오류메시지가 뜨는 문제를 해결했어요.
- 비밀번호 찾기 페이지에서 이메일 유효성을 검사하도록 추가했어요.
- 비밀번호 찾기 페이지에서 가입되지 않은 이메일로 요청을 보냈을 때 에러메시지를 추가했어요.
- 비밀번호 변경 페이지에서 현재 비밀번호와 새 비밀번호가 똑같을 때 에러메시지를 띄우도록 추가했어요.
- 비밀번호 변경 페이지에서 현재 비밀번호, 새 비밀번호의 유효성검사 기능을 추가했어요.
- 회원가입 페이지에서 전화번호, 이메일, 비밀번호 유효성 검사를 추가했어요.
마이페이지에서 로그아웃, 회원탈퇴 진행 시 리다이렉트 되는 코드가 추가되었는데 간단한 작업이라 이번 PR에 추가했어요.
> [#346] 이메일 비밀번호 유효성 검사 추가

- App/Sources/DesignSystem/View/DetailView.swift
- App/Sources/DesignSystem/View/LinkDetailSettingView.swift
- App/Sources/Feature/AdminUserListFeature/Source/AdminUserListViewModel.swift
- App/Sources/Feature/ClubListFeature/Source/ClubListView.swift
- App/Sources/Feature/ClubListFeature/Source/Component/SchoolListView.swift
- App/Sources/Feature/InquiryListFeature/Source/InquiryListView.swift
- App/Sources/Feature/InquiryListFeature/Source/InquiryListViewModel.swift
- App/Sources/Feature/NoticeDetailFeature/Source/NoticeDetailView.swift
- App/Sources/Feature/NoticeDetailSettingFeature/Source/NoticeDetailSettingView.swift
- App/Sources/Feature/NoticeDetailSettingFeature/Source/NoticeDetailSettingViewModel.swift
- App/Sources/Feature/NoticeListFeature/Source/NoticeListView.swift
- App/Sources/Feature/NoticeListFeature/Source/NoticeListViewModel.swift
- App/Sources/Feature/PostDetailFeature/Source/PostDetailView.swift
- App/Sources/Feature/PostDetailSettingFeature/Source/PostDetailSettingView.swift
- App/Sources/Feature/PostDetailSettingFeature/Source/PostDetailSettingViewModel.swift
- App/Sources/Feature/PostListFeature/Sources/PostListView.swift
- App/Sources/Feature/PostListFeature/Sources/PostListViewModel.swift
- App/Sources/Feature/StudentInfoFeature/Source/Component/CertificationListRow.swift
- App/Sources/Utils/Extensions/Array+safe.swift
- Service/Sources/Domain/ClubDomain/DTO/Response/ClubResponseDTO.swift
- Service/Sources/Domain/PostDomain/DTO/Response/PostDetailResponseDTO.swift
- Service/Sources/Domain/PostDomain/Entity/PostDetailEntity.swift
- Service/Sources/Domain/SchoolDoamin/API/SchoolAPI.swift
- 게시글, 공지사항 세부설정 페이지에서 링크를 추가하는 부분에서 URL 유효성을 검사하는 기능을 추가하는 게 좋을 것 같다는 QA 피드백
- 게시글, 공지사항 상세 페이지에서 관련 링크보기 부분에 줄 정렬이 center로 되어있는 부분
- 문의 사항이 목록 페이지에서 문의사항이 없을 때 NoInfoView가 위로 올라가 있는 문제
- 게시글, 공지사항 상세페이지에 게시날짜, 게시자 추가 디자인 반영
QA진행 중에 나온 피드백들을 반영해야해요.
Resolves: #350 
- 게시글, 공지사항 세부설정 페이지 링크 유효성 검사 기능 추가
- 게시글, 공지사항 상세 페이지 관련 링크보기 줄 정렬 변경
- 문의사항 목록 페이지에서 문의사항의 없을 때 NoInfoView 위치 변경
- 게시글, 공지사항 상세 페이지 게시날짜, 게시자 디자인변경 반영
> 🔀 :: [#350] URL 유효성 검사 기능 추가

- App/Sources/DesignSystem/View/DetailView.swift
- App/Sources/DesignSystem/View/LinkDetailSettingView.swift
- App/Sources/Feature/AdminUserListFeature/Source/AdminUserListViewModel.swift
- App/Sources/Feature/AdminUserListFeature/Source/Component/UserTypeFilterPopup.swift
- App/Sources/Feature/AdminWithdrawUserListFeature/Source/Component/UserCohortFilterPopup.swift
- App/Sources/Feature/ClubListFeature/Source/ClubListView.swift
- App/Sources/Feature/ClubListFeature/Source/Component/SchoolListView.swift
- App/Sources/Feature/InquiryListFeature/Source/Component/AnswerFilterPopup.swift
- App/Sources/Feature/InquiryListFeature/Source/InquiryListView.swift
- App/Sources/Feature/InquiryListFeature/Source/InquiryListViewModel.swift
- App/Sources/Feature/NoticeDetailFeature/Source/NoticeDetailView.swift
- App/Sources/Feature/NoticeDetailSettingFeature/Source/NoticeDetailSettingView.swift
- App/Sources/Feature/NoticeDetailSettingFeature/Source/NoticeDetailSettingViewModel.swift
- App/Sources/Feature/NoticeListFeature/Source/NoticeListView.swift
- App/Sources/Feature/NoticeListFeature/Source/NoticeListViewModel.swift
- App/Sources/Feature/PostDetailFeature/Source/PostDetailView.swift
- App/Sources/Feature/PostDetailSettingFeature/Source/PostDetailSettingView.swift
- App/Sources/Feature/PostDetailSettingFeature/Source/PostDetailSettingViewModel.swift
- App/Sources/Feature/PostListFeature/Sources/PostListView.swift
- App/Sources/Feature/PostListFeature/Sources/PostListViewModel.swift
- App/Sources/Feature/SignUpFeature/SignUpView.swift
- App/Sources/Feature/SignUpFeature/View/SchoolListRow.swift
- App/Sources/Feature/SignUpFeature/View/SearchClubListBottomSheet.swift
- App/Sources/Feature/SignUpFeature/View/SearchClubListRow.swift
- App/Sources/Feature/StudentInfoFeature/Source/Component/CertificationListRow.swift
- App/Sources/Utils/Extensions/Array+safe.swift
- Service/Sources/Domain/ClubDomain/DTO/Response/ClubResponseDTO.swift
- Service/Sources/Domain/PostDomain/DTO/Response/PostDetailResponseDTO.swift
- Service/Sources/Domain/PostDomain/Entity/PostDetailEntity.swift
- Service/Sources/Domain/SchoolDoamin/API/SchoolAPI.swift
기존의 라디오 버튼으로 선택할 때 범위가 좁아 버튼을 선택하는 데 불편함을 겪었어요.
Resolves: #350 
라디오 버튼이 사용되는 부분들에 onTapGesture를 한 번 더 감싸 더 넒은 범위에서 선택해도 선택되도록 수정했어요.
> 🔀 :: [#350] 라디오 버튼 선택 범위 확장

- App/Sources/Application/DI/Lecture/AppComponent+Lecture.swift
- App/Sources/Application/NeedleGenerated.swift
- App/Sources/Feature/ClubDetailFaeture/Source/ClubDetailView.swift
- App/Sources/Feature/ClubDetailFaeture/Source/ClubDetailViewModel.swift
- App/Sources/Feature/LectureListDetailFeature/LectureListDetailView.swift
- App/Sources/Feature/LectureListDetailFeature/LectureListDetailViewModel.swift
- App/Sources/Feature/LectureListDetailFeature/Source/LectureListDetailComponent.swift
- App/Sources/Feature/SignUpFeature/SignUpView.swift
- App/Sources/Feature/SignUpFeature/SignUpViewModel.swift
- Service/Project.swift
- Service/Sources/Data/DataSource/Lecture/RemoteLectureDataSourceImpl.swift
- Service/Sources/Data/Repository/Lecture/LectureRepositoryImpl.swift
- Service/Sources/Data/UseCase/Lecture/DeleteLectureUseCaseImpl.swift
- Service/Sources/Domain/ClubDomain/DTO/Response/ClubDetailResponseDTO.swift
- Service/Sources/Domain/ClubDomain/Entity/ClubDetailEntity.swift
- Service/Sources/Domain/LectureDomain/API/LectureAPI.swift
- Service/Sources/Domain/LectureDomain/DataSource/RemoteLectureDataSource.swift
- Service/Sources/Domain/LectureDomain/Repository/LectureRepository.swift
- Service/Sources/Domain/LectureDomain/UseCase/DeleteLectureUseCase.swift
- Service/Sources/Testing/UseCase/FetchClubDetailUseCaseStub.swift
- Service/Sources/Testing/UseCase/FetchStudentListByClubUseCaseStub.swift
- Tuist/ProjectDescriptionHelpers/DynamicFramwork.swift
- Tuist/ProjectDescriptionHelpers/Enum/GenerateEnvironment.swift
강의 삭제 기능이 추가되고 디자인이 변경되어서 적용했어요.
Resolves: #354 
- 강의 삭제 기능을 추가했어요.
- 유관기관 회원가입 테스트 중 회원가입이 안되는 오류가 있어서 확인해보니 동아리 입력 필드가 빠져있어서 추가해서 유관기관 회원가입이 가능하게 변경했어요.
- 동아리 상세 조회가 되지 않아서 확인해보니 highSchoolName -> schoolName으로 필드가 변경되어서 데이터를 가져올 수 없는 이슈여서 fix했어요!!
> 🔀 :: [#354] 강의 삭제 기능 추가

- .github/workflows/bitgouel-ios-ci.yml
- App/Sources/Application/DI/Government/AppComponent+Government.swift
- App/Sources/Application/NeedleGenerated.swift
- Service/Sources/Base/BitgouelAPI.swift
- Service/Sources/Data/DataSource/Government/RemoteGovernmentDataSourceImpl.swift
- Service/Sources/Data/Repository/Government/GovernmentRepositoryImpl.swift
- Service/Sources/Data/UseCase/Government/CreatedGovernmentUseCaseImpl.swift
- Service/Sources/Data/UseCase/Government/DeleteGovernmentUseCaseImpl.swift
- Service/Sources/Data/UseCase/Government/FetchGovernmentUseCaseImpl.swift
- Service/Sources/Domain/GovernmentDomain/API/GovernmentAPI.swift
- Service/Sources/Domain/GovernmentDomain/DTO/Request/CreatedGovernmentRequestDTO.swift
- Service/Sources/Domain/GovernmentDomain/DTO/Response/GovernmentListResponseDTO.swift
- Service/Sources/Domain/GovernmentDomain/DataSource/RemoteGovernmentDataSource.swift
- Service/Sources/Domain/GovernmentDomain/Entity/GovernmentInfoEntity.swift
- Service/Sources/Domain/GovernmentDomain/Error/GovernmentDomainError.swift
- Service/Sources/Domain/GovernmentDomain/Repository/GovernmentRepository.swift
- Service/Sources/Domain/GovernmentDomain/UseCase/CreatedGovernmentUseCase.swift
- Service/Sources/Domain/GovernmentDomain/UseCase/DeleteGovernmentUseCase.swift
- Service/Sources/Domain/GovernmentDomain/UseCase/FetchGovernmentListUseCase.swift
유관기관 CRUD기능이 추가되어 API 세팅이 필요합니다...!
Resolves: #372 
- 유관기관 리스트 조회
- 유관기관 생성
- 유관기관 삭제
위의 API들을 세팅했습니다.
> 🔀 :: [#372] government 도메인 세팅

- App/Sources/Application/NeedleGenerated.swift
- App/Sources/Feature/SchoolListFeature/Source/SchoolListComponent.swift
- App/Sources/Feature/SchoolListFeature/Source/SchoolListView.swift
- App/Sources/Feature/SchoolListFeature/Source/SchoolListViewModel.swift
- Service/Sources/Domain/SchoolDoamin/DTO/Response/SchoolListResponseDTO.swift
학교 목록페이지에 학교 리스트 조회 기능을 추가해야해요.
Resolves: #377 
https://github.com/user-attachments/assets/0ae1e872-d09b-4294-8dbf-8dc9de2a9eed
- 학교 목록페이지에 학교 리스트 조회 기능을 추가해 퍼블리싱 된 UI와 연결했습니다.
- SchoolListResponseDTO에 schoolName이 서버에서는 name으로 와서 codingKeys로 맞춰줬습니다.
> 🔀 :: [#377] 학교 목록 - 학교 리스트 조회 기능 추가

- App/Sources/Feature/AdminBaseFeature/Source/Component/View/CountHeader.swift
- App/Sources/Feature/OrganizationListFeature/Source/OrganizationListView.swift
- App/Sources/Feature/SchoolListFeature/Source/SchoolListView.swift
- App/Sources/Feature/UniversityListFeature/Source/Component/UniversityDetailBottomSheet.swift
- App/Sources/Feature/UniversityListFeature/Source/UniversityListView.swift
- App/Sources/Feature/UniversityListFeature/Source/UniversityListViewModel.swift
- Service/Sources/Domain/UniversityDomain/DTO/Response/UniversityListResponseDTO.swift
- Service/Sources/Domain/UniversityDomain/Entity/UniversityInfoEntity.swift
https://github.com/user-attachments/assets/1fe04056-de1d-4ee7-9838-b25a2d8fa17b
Resolves: #386 
- 대학 목록 페이지를 퍼블리싱 했어요.
- 총 N개의 대학... 기업 등 각 페이지의 목록마다 기업이 몇개가 있는지 알려주는 부분의 코드가 계속 반복되어서 CountHeader로 Component화 했어요.
- universityID의 Type을 String에서 Int로 변경했어요.
> 🔀 :: [#386] 대학 목록 페이지 퍼블리싱

- App/Sources/Application/NeedleGenerated.swift
- App/Sources/Feature/UniversityListFeature/Source/UniversityListComponent.swift
- App/Sources/Feature/UniversityListFeature/Source/UniversityListView.swift
- App/Sources/Feature/UniversityListFeature/Source/UniversityListViewModel.swift
Resolves: #386 
- 대학 목록페이지에 대학 학과 리스트 조회 기능을 추가했어요.
> 🔀 :: [#386] 대학 학과 리스트 조회 기능 추가

- App/Sources/Application/DI/AppComponent.swift
- App/Sources/Application/NeedleGenerated.swift
- App/Sources/Feature/InputUniversityFeature/Interface/InputUniversityFactory.swift
- App/Sources/Feature/InputUniversityFeature/Source/InputUniversityComponent.swift
- App/Sources/Feature/InputUniversityFeature/Source/InputUniversityView.swift
- App/Sources/Feature/InputUniversityFeature/Source/InputUniversityViewModel.swift
- App/Sources/Feature/OrganizationListFeature/Source/OrganizationListView.swift
- App/Sources/Feature/OrganizationListFeature/Source/OrganizationListViewModel.swift
- App/Sources/Feature/UniversityListFeature/Source/UniversityListComponent.swift
- App/Sources/Feature/UniversityListFeature/Source/UniversityListView.swift
- App/Sources/Feature/UniversityListFeature/Source/UniversityListViewModel.swift
대학 등록, 수정 페이지가 학과 목록의 차이 빼고는 UI가 같아서 InputUniversityFeature 하나로 관리할 수 있도록 했어요.
Resolves: #386 
https://github.com/user-attachments/assets/6e27d323-560e-4c46-8a01-3505c933b8e1
대학 등록, 수정 페이지를 퍼블리싱 했어요.
> 🔀 :: [#386] 대학 입력 페이지 퍼블리싱

- App/Sources/Application/NeedleGenerated.swift
- App/Sources/Feature/InputOrganizationFeature/Source/InputOrganizationComponent.swift
- App/Sources/Feature/InputUniversityFeature/Source/Component/InputDepartmentView.swift
- App/Sources/Feature/InputUniversityFeature/Source/InputUniversityComponent.swift
- App/Sources/Feature/InputUniversityFeature/Source/InputUniversityView.swift
- App/Sources/Feature/InputUniversityFeature/Source/InputUniversityViewModel.swift
- App/Sources/Feature/OrganizationListFeature/Source/OrganizationListComponent.swift
- App/Sources/Feature/UniversityListFeature/Source/UniversityListComponent.swift
- App/Sources/Feature/UniversityListFeature/Source/UniversityListView.swift
- App/Sources/Utils/Extensions/Error+DomainErrorMessage.swift
- Service/Sources/Data/DataSource/University/RemoteUniversityDataSourceImpl.swift
- Service/Sources/Data/Repository/University/UniversityRepositoryImpl.swift
- Service/Sources/Data/UseCase/University/CreatedDepartmentUseCaseImpl.swift
- Service/Sources/Data/UseCase/University/DeleteDepartmentUseCaseImpl.swift
- Service/Sources/Data/UseCase/University/DeleteUniversityUseCaseImpl.swift
- Service/Sources/Data/UseCase/University/ModifyUniversityUseCaseImpl.swift
- Service/Sources/Domain/UniversityDomain/API/UniversityAPI.swift
- Service/Sources/Domain/UniversityDomain/DTO/Request/DepartmentRequestDTO.swift
- Service/Sources/Domain/UniversityDomain/DTO/Request/UniversityNameRequestDTO.swift
- Service/Sources/Domain/UniversityDomain/DataSource/RemoteUniversityDataSource.swift
- Service/Sources/Domain/UniversityDomain/Repository/UniversityRepository.swift
- Service/Sources/Domain/UniversityDomain/UseCase/CreatedDepartmentUseCase.swift
- Service/Sources/Domain/UniversityDomain/UseCase/DeleteDepartmentUseCase.swift
- Service/Sources/Domain/UniversityDomain/UseCase/DeleteUniversityUseCase.swift
- Service/Sources/Domain/UniversityDomain/UseCase/ModifyUniversityUseCase.swift
대학 등록 페이지에 대학 삭제, 수정, 등록, 학과 생성, 삭제 기능을 추가했어요.
Resolves: #386 
- 대학 등록
- 대학 삭제
- 대학 수정
- 학과 생성
- 학과 삭제
위 기능들을 추가했어요.
- universityDomainErrorMessage() Util을 추가했어요!
- UniversityID의 Type이 String으로 되어있어서 Int로 변경했어요!
- 대학 목록 페이지 -> 대학 상세 BottomSheet -> 대학 수정 페이지 이동 후 다시 대학 목록 페이지로 이동했을 때
BottomSheet가 내려가지 않아서 삭제된 대학의 상세 BottomSheet가 보이게 되거나, 수정된 내용이 적용되지 않은 상세 BottomSheet가 보이게 되는 문제가 발생해서 대학 수정 페이지로 이동했을 때 BottomSheet가 내려가도록 수정했어요.
- 학과 생성, 삭제 시 서버로 다시 리스트 조회 요청을 보내 학과 List를 받기에는 불필요한 요청이 많아질 것 같고, 대학이 많아졌을 때 선택한 대학의 id를 찾는 과정이 복잡해질 것 같다고 판단해서 처음 서버에서 받은 DepartmentList에 클라이언트에서 append 및 remove를 하도록 진행했어요! 감안하고 리뷰해주세요.
> 🔀 :: [#386] 대학 입력 페이지 기능 추가

- App/Sources/Application/NeedleGenerated.swift
- App/Sources/Feature/InputSchoolFeature/Source/Component/CreatedSchoolSuccessView.swift
- App/Sources/Feature/InputSchoolFeature/Source/Component/SchoolLineBottomSheet.swift
- App/Sources/Feature/InputSchoolFeature/Source/InputSchoolComponent.swift
- App/Sources/Feature/InputSchoolFeature/Source/InputSchoolView.swift
- App/Sources/Feature/InputSchoolFeature/Source/InputSchoolViewModel.swift
- App/Sources/Feature/SchoolListFeature/Source/SchoolListView.swift
- App/Sources/Utils/Extensions/Error+DomainErrorMessage.swift
- Service/Sources/Data/DataSource/School/RemoteSchoolDataSourceImpl.swift
- Service/Sources/Data/Repository/School/SchoolRepositoryImpl.swift
- Service/Sources/Data/UseCase/School/CreatedSchoolUseCaseImpl.swift
- Service/Sources/Data/UseCase/School/ModifySchoolUseCaseImpl.swift
- Service/Sources/Domain/SchoolDoamin/API/SchoolAPI.swift
- Service/Sources/Domain/SchoolDoamin/DTO/Request/CreatedSchoolRequestDTO.swift
- Service/Sources/Domain/SchoolDoamin/DTO/Request/InputSchoolInfoRequestDTO.swift
- Service/Sources/Domain/SchoolDoamin/DTO/Request/ModifySchoolRequestDTO.swift
- Service/Sources/Domain/SchoolDoamin/DTO/Response/SchoolListResponseDTO.swift
- Service/Sources/Domain/SchoolDoamin/DataSource/RemoteSchoolDataSource.swift
- Service/Sources/Domain/SchoolDoamin/Repository/SchoolRepository.swift
- Service/Sources/Domain/SchoolDoamin/UseCase/CreatedSchoolUseCase.swift
- Service/Sources/Domain/SchoolDoamin/UseCase/ModifySchoolUseCase.swift
학교 정보 입력 페이지에 기능을 추가했어요
Resolves: #391 
- 학교 생성
- 학교 수정
- 학교 삭제
위 기능들을 추가했어요.
CreatedSchoolRequestDTO, ModifySchoolReqestDTO 두 개로 나누어져있던 requestDTO를 InputSchoolInfoRequestDTO 하나로 사용하도록 변경했어요.
InputSchoolInfoRequestDTO에서 logoImage를 분리했어요.
SchoolLineBottomSheet의 RadioButton 선택범위가 좁아서 더 넓혀줬어요.
> 🔀 :: [#391] 학교 정보 입력 기능 추가

- App/Sources/Application/NeedleGenerated.swift
- App/Sources/Feature/LectureApplicantListFeature/Source/Component/ApplicantStudentDetailBottomSheet.swift
- App/Sources/Feature/LectureApplicantListFeature/Source/LectureApplicantListComponent.swift
- App/Sources/Feature/LectureApplicantListFeature/Source/LectureApplicantListView.swift
- App/Sources/Feature/LectureApplicantListFeature/Source/LectureApplicantListViewModel.swift
- Service/Sources/Data/DataSource/Lecture/RemoteLectureDataSourceImpl.swift
- Service/Sources/Data/Repository/Lecture/LectureRepositoryImpl.swift
- Service/Sources/Data/UseCase/Lecture/SetLectureCompletionUseCaseImpl.swift
- Service/Sources/Domain/LectureDomain/API/LectureAPI.swift
- Service/Sources/Domain/LectureDomain/DTO/Response/AppliedLectureStudentDetailResponseDTO.swift
- Service/Sources/Domain/LectureDomain/DataSource/RemoteLectureDataSource.swift
- Service/Sources/Domain/LectureDomain/Entity/ApplicantInfoEntity.swift
- Service/Sources/Domain/LectureDomain/Entity/AppliedLectureStudentDetailEntity.swift
- Service/Sources/Domain/LectureDomain/Repository/LectureRepository.swift
- Service/Sources/Domain/LectureDomain/UseCase/SetLectureCompletionUseCase.swift
강의 신청자 명단 페이지 디자인이 변경되었어요.
Resolves: #398 
https://github.com/user-attachments/assets/ab9539c2-3314-48dd-aa88-52270949c51c
- 변경된 강의 신청자 명단 페이지의 디자인을 적용했어요.
- 강의 이수중인 학생 상세조회 기능을 추가해서 BottomSheet로 강의 이수중인 학생의 상세 정보를 보여주도록 했어요.
- currentCompletedDate가 옵셔널 처리가 되어있지 않아서 추가했어요.
> 🔀 :: [#398] 강의 신청자 명단 페이지 디자인 변경사항 적용

- App/Sources/Feature/InputLectureFeature/Sources/InputLectureViewModel.swift
- App/Sources/Feature/InputLectureFeature/Sources/Model/LectureDataModel.swift
- App/Sources/Feature/LectureDetailSettingFeature/Sources/Component/View/ApplicationPeriodView.swift
- App/Sources/Feature/LectureDetailSettingFeature/Sources/Component/View/LectureLocationView.swift
- App/Sources/Feature/LectureDetailSettingFeature/Sources/LectureDetailSettingView.swift
- App/Sources/Feature/LectureDetailSettingFeature/Sources/LectureDetailSettingViewModel.swift
- App/Sources/Utils/View/KakaoPostCodeView.swift
- Service/Sources/Domain/LectureDomain/DTO/Request/InputLectureRequestDTO.swift
강의 개설 시 상세 정보 설정 페이지에서 강의 장소를 우편번호로 검색하는 기능이 추가되었어요.
Resolves: #395 
https://github.com/user-attachments/assets/efa129e3-c00b-461f-afd0-8163059d3f27
- 강의 장소 Section이 추가되었어요.
- 우편번호 검색 View를 추가했어요.
- InputLectureRequestDTO에 address, locationDetails, essentialComplete를 추가했어요.
> 🔀 :: [#395] 강의 장소 우편번호 검색 기능 추가
