- .github/workflows/bitgouel-ios-ci.yml
- App/Sources/Application/BitgouelApp.swift
CI 스크립트를 작성하였습니다.
SMS IOS CI 스크립트 "참고하여" CI스크립트를 작성하였습니다.
> 💚 :: CI 스크립트 작성

- App/Sources/DesignSystem/Font/Font+Bitgouel.swift
Font에 Color 설정 기능을 추가했습니다.
bitgouelFont를 사용해서 foregroundColor까지 설정할 수 있도록 추가했습니다.
```Swift
Text("하하")
.bitgouelFont(.title1, color: .error(.e1))
```
> 🔀 :: [#18] DesignSystem / Font에 color 설정 기능 추가

- App/Sources/DesignSystem/Text/BitgouelText.swift
DesignSystem에 BitgouelText를 제작했습니다.
BitgouelText 제작
```Swift
BitgouelText(text: "이렇게!", font: .title1)
```
> 🔀 :: [#12] DesignSystem / BitgouelText 제작

- App/Sources/DesignSystem/Button/BitgouelButton.swift
DesignSystem에 Button 추가
DesignSystem에 Button을 추가했습니다.
> 🔀 ::[#23] DesignSystem에 Button 추가

- Service/Sources/Data/Repository/Auth/AuthRepositoryImpl.swift
- Service/Sources/Data/UseCase/Auth/LogoutUseCaseImpl.swift
- Service/Sources/Domain/AuthDomain/DataSource/RemoteAuthDataSource.swift
- Service/Sources/Domain/AuthDomain/Repository/AuthRepository.swift
- Service/Sources/Domain/AuthDomain/UseCase/LogoutUseCase.swift
> 🔀:: [#38] 로그아웃 기능 추가

- Service/Sources/Data/Repository/Auth/AuthRepositoryImpl.swift
- Service/Sources/Data/UseCase/Auth/ReissueTokenUseCaseImpl.swift
- Service/Sources/Domain/AuthDomain/DataSource/RemoteAuthDataSource.swift
- Service/Sources/Domain/AuthDomain/Repository/AuthRepository.swift
- Service/Sources/Domain/AuthDomain/UseCase/ReissueTokenUseCase.swift
토큰 재발급 기능 추가
토큰 재발급 기능을 추가했습니다.
> 🔀 :: [#36] 토큰 재발급 기능 추가

- App/Sources/DesignSystem/TextField/SecureBitgoeulTextField.swift
- Service/Sources/Data/Repository/Auth/AuthRepositoryImpl.swift
- Service/Sources/Data/UseCase/Auth/TeacherSignupUseCaseImpl.swift
- Service/Sources/Domain/AuthDomain/DataSource/RemoteAuthDataSource.swift
- Service/Sources/Domain/AuthDomain/Repository/AuthRepository.swift
- Service/Sources/Domain/AuthDomain/UseCase/TeacherSignupUseCase.swift
취동쌤 회원가입 기능 추가
취동쌤 회원가입 기능을 추가했습니다.
> 🔀 :: [#43] 취동쌤 회원가입 기능 추가

- Service/Sources/Data/Repository/Auth/AuthRepositoryImpl.swift
- Service/Sources/Data/UseCase/Auth/ProfessorSignupUseCaseImpl.swift
- Service/Sources/Domain/AuthDomain/DataSource/RemoteAuthDataSource.swift
- Service/Sources/Domain/AuthDomain/Repository/AuthRepository.swift
- Service/Sources/Domain/AuthDomain/UseCase/ProfessorSignupUseCase.swift
대학교수 회원가입 기능 추가
대학교수 회원가입 기능을 추가했습니다.
> 🔀 :: [#45] 대학교수 회원가입 기능 추가

- Service/Sources/Data/Repository/Auth/AuthRepositoryImpl.swift
- Service/Sources/Data/UseCase/Auth/GovernmentSignupUseCaseImpl.swift
- Service/Sources/Domain/AuthDomain/API/AuthAPI.swift
- Service/Sources/Domain/AuthDomain/DTO/Request/GovernmentSignupRequestDTO.swift
- Service/Sources/Domain/AuthDomain/DataSource/RemoteAuthDataSource.swift
- Service/Sources/Domain/AuthDomain/Repository/AuthRepository.swift
- Service/Sources/Domain/AuthDomain/UseCase/GovernmentSignupUseCase.swift
유관 기관 회원가입 기능 추가
유관 기관 회원가입 기능을 추가했습니다.
GrovernmentRequestDTO -> GovernmentRequestDTO
오타를 수정했습니다.
> 🔀 :: [#47] 유관 기관 회원가입 기능 추가

- Service/Sources/Data/Repository/Auth/AuthRepositoryImpl.swift
- Service/Sources/Data/UseCase/Auth/CompanyInstructorSignupUseCaseImpl.swift
- Service/Sources/Domain/AuthDomain/DataSource/RemoteAuthDataSource.swift
- Service/Sources/Domain/AuthDomain/Repository/AuthRepository.swift
- Service/Sources/Domain/AuthDomain/UseCase/CompanyInstructorSignupUseCase.swift
기업 강사 회원가입 기능 추가
기업 강사 회원가입 기능을 추가했습니다.
> 🔀 :: [#51] 기업 강사 회원가입 기능 추가

- Service/Sources/Base/Enum/LectureType.swift
- Service/Sources/Data/Repository/Auth/AuthRepositoryImpl.swift
- Service/Sources/Data/Repository/Lecture/LectureRepositoryImpl.swift
- Service/Sources/Data/UseCase/Lecture/LectureOpenUseCaseImpl.swift
- Service/Sources/Domain/AuthDomain/API/AuthAPI.swift
- Service/Sources/Domain/LectureDomain/API/LectureAPI.swift
- Service/Sources/Domain/LectureDomain/DTO/Request/LectureOpenRequestDTO.swift
- Service/Sources/Domain/LectureDomain/DataSource/RemoteLectureDataSource.swift
- Service/Sources/Domain/LectureDomain/Error/LectureDomainError.swift
- Service/Sources/Domain/LectureDomain/Repository/LectureRepository.swift
- Service/Sources/Domain/LectureDomain/UseCase/LectureOpenUseCase.swift
lectureDomain 세팅
LectureDomain을 세팅했습니다.
AuthAPI 부분에 withdraw, logout을 accessToken으로 변경했습니다.
> 🔀 :: [#55] LectureDomain 세팅

- App/Sources/DesignSystem/Button/BitgouelButton.swift
- App/Sources/DesignSystem/Button/BitgouelButtonStyle.swift
- Service/Sources/Data/Repository/Lecture/LectureRepositoryImpl.swift
- Service/Sources/Data/UseCase/Lecture/LectureOpenUseCaseImpl.swift
- Service/Sources/Domain/LectureDomain/DataSource/RemoteLectureDataSource.swift
- Service/Sources/Domain/LectureDomain/Repository/LectureRepository.swift
- Service/Sources/Domain/LectureDomain/UseCase/LectureOpenUseCase.swift
> 🔀 :: [#57] 강의 개설 기능 추가

- App/Sources/DesignSystem/BottomSheet/BitgouelBottomSheet.swift
- App/Sources/DesignSystem/Extensions/View+cornerRadius.swift
- Service/Sources/Data/Repository/Lecture/LectureRepositoryImpl.swift
- Service/Sources/Data/UseCase/Lecture/LectureApplyUseCaseImpl.swift
- Service/Sources/Data/UseCase/Lecture/WaitingLectureApproveUseCaseImpl.swift
- Service/Sources/Data/UseCase/Lecture/WaitingLectureRejectUseCaseImpl.swift
- Service/Sources/Domain/LectureDomain/API/LectureAPI.swift
- Service/Sources/Domain/LectureDomain/DataSource/RemoteLectureDataSource.swift
- Service/Sources/Domain/LectureDomain/Error/LectureDomainError.swift
- Service/Sources/Domain/LectureDomain/Repository/LectureRepository.swift
- Service/Sources/Domain/LectureDomain/UseCase/LectureApplyUseCase.swift
- Service/Sources/Domain/LectureDomain/UseCase/WaitingLectureRejectUseCase.swift
- Service/Sources/Domain/LectureDomain/UseCase/WaitingLectureUseCase.swift
LectureDomain 기능 추가
- 강의 신청
- 대기 중인 강의 수락
- 대기 중인 강의 거절
기능을 추가했습니다.
> 🔀 :: [#59] LectureDomain 기능 추가

- Service/Sources/Data/Repository/Auth/AuthRepositoryImpl.swift
- Service/Sources/Data/UseCase/Auth/BbozzakSignupUseCaseImpl.swift
- Service/Sources/Domain/AuthDomain/API/AuthAPI.swift
- Service/Sources/Domain/AuthDomain/DTO/Request/BbozzakSignupRequestDTO.swift
- Service/Sources/Domain/AuthDomain/DataSource/RemoteAuthDataSource.swift
- Service/Sources/Domain/AuthDomain/Repository/AuthRepository.swift
- Service/Sources/Domain/AuthDomain/UseCase/BbozzakSignupUseCase.swift
뽀짝쌤 회원가입 기능을 추가
뽀짝쌤 회원가입 기능을 추가했습니다.
> 🔀 :: [#69] 뽀짝쌤 회원가입 기능 추가

- App/Sources/DesignSystem/Button/ListSelectButton/AssociationSelectButton.swift
- App/Sources/DesignSystem/Button/ListSelectButton/AssociationSelectButtonStyle.swift
- App/Sources/DesignSystem/Button/RadioButton/BitgouelRadioButton.swift
- App/Sources/DesignSystem/Button/RadioButton/PressedSelectionButtonStyle.swift
- App/Sources/DesignSystem/TextField/BitgoeulTextField.swift
- App/Sources/DesignSystem/TextField/SecureBitgoeulTextField.swift
- App/Sources/Feature/LoginFeature/LoginView.swift
- App/Sources/Feature/LoginFeature/LoginViewModel.swift
- Service/Sources/Base/Enum/LectureStatusType.swift
- Service/Sources/Data/Repository/Auth/AuthRepositoryImpl.swift
- Service/Sources/Data/Repository/Lecture/LectureRepositoryImpl.swift
- Service/Sources/Data/UseCase/Auth/BbozzakSignupUseCaseImpl.swift
- Service/Sources/Data/UseCase/Lecture/LectureDetailInquiryUseCaseImpl.swift
- Service/Sources/Data/UseCase/Lecture/LectureListInquirtyUseCaseImpl.swift
- Service/Sources/Domain/AuthDomain/API/AuthAPI.swift
- Service/Sources/Domain/AuthDomain/DTO/Request/BbozzakSignupRequestDTO.swift
- Service/Sources/Domain/AuthDomain/DataSource/RemoteAuthDataSource.swift
- Service/Sources/Domain/LectureDomain/API/LectureAPI.swift
- Service/Sources/Domain/LectureDomain/DTO/Response/FetchLectureDeailResponseDTO.swift
- Service/Sources/Domain/LectureDomain/DTO/Response/FetchLectureListResponseDTO.swift
- Service/Sources/Domain/LectureDomain/DataSource/RemoteLectureDataSource.swift
- Service/Sources/Domain/LectureDomain/Entity/LectureDetailEntity.swift
- Service/Sources/Domain/LectureDomain/Entity/LectureListEntity.swift
- Service/Sources/Domain/LectureDomain/Repository/LectureRepository.swift
- Service/Sources/Domain/LectureDomain/UseCase/LectureDetailInquiryUseCase.swift
- Service/Sources/Domain/LectureDomain/UseCase/LectureListInquirtyUseCase.swift
강의 조회 기능을 추가했습니다.
- 강의 리스트 조회 기능 추가
- 강의 상세정보 조회 기능을 추가했습니다.
- LectureStatus Enum이 추가되지 않아 있어서 추가했습니다.
> 🔀 :: [#73] 강의 조회 기능 추가

- .github/workflows/bitgouel-ios-ci.yml
오류 디버깅 로그를 더 상세하게 띄워주기위해서 옵션을 추가하겠습니다.
> Test Tuist verbose 옵션 추가

- App/Sources/Application/BitgouelApp.swift
- App/Sources/Feature/LoginFeature/LoginViewModel.swift
HelpMessage 따로 분리
텍스트필드가 작동하지 않아 helpMessage를 따로 분리했습니다.
> 🔀 :: HelpMessage 따로 분리

- App/Sources/DesignSystem/Button/BitgouelButton/BitgouelButton.swift
BitgouelButton의 생성자를 수정했습니다.
BitgouelButton 생성자의 self.style = .primary 에서  self.style = style 로 수정했습니다.
> 🔀 :: [#86] BitgouelButton의 생성자 수정

- Service/Sources/Domain/LectureDomain/DTO/Response/FetchLectureDeailResponseDTO.swift
- Service/Sources/Domain/LectureDomain/Entity/LectureDetailEntity.swift
LectureDomain에 isRegistered 추가
변경된 API에 맞춰서 LectureDtail에 isRegistered를 추가했습니다.
> 🔀 :: [#98] LectureDomain에 isRegistered 추가

- App/Sources/Feature/StudentSignUpFeature/StudentSignUpView.swift
- App/Sources/Feature/StudentSignUpFeature/StudentSignUpViewModel.swift
학생 회원가입 로직에 공통 회원가입 로직 추가
- 조직 선택 기능 추가
- 직업 선택 기능 추가
다른 리팩토링 작업 PR도 올릴 예정이에요
> 🔀 :: [#79] 학생 회원가입 로직에 공통 회원가입 로직 추가

- App/Sources/Application/DI/User/AppComponent+User.swift
- App/Sources/Application/NeedleGenerated.swift
- Service/Sources/Data/DataSource/User/RemoteUserDataSourceImpl.swift
- Service/Sources/Data/Repository/User/UserRepositoryImpl.swift
- Service/Sources/Data/UseCase/User/ChangePasswordUseCaseImpl.swift
- Service/Sources/Data/UseCase/User/QueryMyInfoUseCaseImpl.swift
- Service/Sources/Domain/UserDomain/API/UserAPI.swift
- Service/Sources/Domain/UserDomain/DTO/Request/ChangePasswordRequestDTO.swift
- Service/Sources/Domain/UserDomain/DTO/Response/InquiryMyInfoResponseDTO.swift
- Service/Sources/Domain/UserDomain/DataSource/RemoteUserDataSource.swift
- Service/Sources/Domain/UserDomain/Entity/MyInfoEntity.swift
- Service/Sources/Domain/UserDomain/Error/UserDomainError.swift
- Service/Sources/Domain/UserDomain/Repository/UserRepository.swift
- Service/Sources/Domain/UserDomain/UseCase/ChangePasswordUseCase.swift
- Service/Sources/Domain/UserDomain/UseCase/QueryMyInfoUseCase.swift
UserDomain API 세팅
UserDomain API를 세팅했습니다.
> 🔀 :: [#124] UserDomain API 세팅

- App/Sources/Application/DI/AppComponent.swift
- App/Sources/Application/NeedleGenerated.swift
- App/Sources/Feature/ActivityDetailSettingFeature/Interface/ActivityDetailSettingFactory.swift
- App/Sources/Feature/ActivityDetailSettingFeature/Sources/ActivityDetailSettingComponent.swift
- App/Sources/Feature/ActivityDetailSettingFeature/Sources/ActivityDetailSettingView.swift
- App/Sources/Feature/ActivityDetailSettingFeature/Sources/ActivityDetailSettingViewModel.swift
- App/Sources/Feature/InputActivityFeature/Source/InputActivityComponent.swift
- App/Sources/Feature/InputActivityFeature/Source/InputActivityView.swift
- App/Sources/Feature/InputActivityFeature/Source/InputActivityViewModel.swift
학생활동 세부설정 기능 추가
- 학생활동 세부설정(날짜 학점)을 설정하는 기능 추가
- 학생활동 추가기능 추가
> 🔀 :: [#103] 학생활동 세부설정 기능 추가

- App/Sources/Application/DI/AppComponent.swift
- App/Sources/Application/DI/Lecture/AppComponent+Lecture.swift
- App/Sources/Application/DI/User/AppComponent+User.swift
- App/Sources/Application/NeedleGenerated.swift
- App/Sources/Feature/ActivityDetailSettingFeature/Sources/ActivityDetailSettingComponent.swift
- App/Sources/Feature/ActivityDetailSettingFeature/Sources/ActivityDetailSettingViewModel.swift
- App/Sources/Feature/InputActivityFeature/Source/InputActivityView.swift
- App/Sources/Feature/InputActivityFeature/Source/InputActivityViewModel.swift
- Service/Sources/Data/DataSource/Lecture/RemoteLectureDataSourceImpl.swift
- Service/Sources/Data/DataSource/User/RemoteUserDataSourceImpl.swift
- Service/Sources/Data/Repository/Lecture/LectureRepositoryImpl.swift
- Service/Sources/Data/Repository/User/UserRepositoryImpl.swift
- Service/Sources/Data/UseCase/Lecture/LectureApplyUseCaseImpl.swift
- Service/Sources/Data/UseCase/Lecture/LectureDetailInquiryUseCaseImpl.swift
- Service/Sources/Data/UseCase/Lecture/LectureListInquirtyUseCaseImpl.swift
- Service/Sources/Data/UseCase/Lecture/LectureOpenUseCaseImpl.swift
- Service/Sources/Data/UseCase/Lecture/WaitingLectureApproveUseCaseImpl.swift
- Service/Sources/Data/UseCase/Lecture/WaitingLectureRejectUseCaseImpl.swift
- Service/Sources/Data/UseCase/User/ChangePasswordUseCaseImpl.swift
- Service/Sources/Data/UseCase/User/QueryMyInfoUseCaseImpl.swift
- Service/Sources/Domain/LectureDomain/DataSource/RemoteLectureDataSource.swift
- Service/Sources/Domain/LectureDomain/UseCase/WaitingLectureUseCase.swift
- Service/Sources/Domain/UserDomain/API/UserAPI.swift
- Service/Sources/Domain/UserDomain/DTO/Request/ChangePasswordRequestDTO.swift
- Service/Sources/Domain/UserDomain/DTO/Response/InquiryMyInfoResponseDTO.swift
- Service/Sources/Domain/UserDomain/Entity/MyInfoEntity.swift
- Service/Sources/Domain/UserDomain/Error/UserDomainError.swift
AppComponent+Lecture 추가
추가하지 못했던 AppComponent+Lecture 추가했습니다.
RemoteLectureDataSourceImpl 파일이 추가되었습니다.
WaitingLectureUseCase에서 WaitingLectureApproveUseCase로 이름이 변경되었습니다.
> 🔀 :: [#134] AppComponent+Lecture 추가

- App/Sources/Feature/ClubListFeature/Source/ClubListView.swift
- App/Sources/Feature/ClubListFeature/Source/Component/ClubListEmptyContentView.swift
> 🔀 :: [#133] 동아리 - 동아리 목록 페이지 EmptyContent 퍼블리싱

- Service/Sources/Base/API/RefreshAPI.swift
- Service/Sources/Base/DataSource/BaseRemoteDataSource.swift
- Service/Sources/Base/Plugins/Jwt/JwtAuthorizable.swift
- Service/Sources/Base/Plugins/Jwt/JwtPlugin.swift
- Service/Sources/Keychain/Sources/KeychainImpl.swift
- Service/Sources/Utils/Date/DateUtil.swift
Token 저장 오류 해결
Token들이 저장되지않던 오류를 해결했습니다.
> 🔀 :: [#148] Token 저장 오류 해결

- App/Sources/DesignSystem/View/DetailView.swift
- App/Sources/DesignSystem/View/InputFormView.swift
- App/Sources/DesignSystem/View/LinkDetailSettingView.swift
- App/Sources/Feature/ActivityDetailFeature/Sources/ActivityDetailView.swift
상세보기 페이지의 UI가 계속 중복되는 부분이 있어서 DesignSystem에 DetailView를추가했어요.
DesignSystem에 DetailView를 추가했어요.
> 🔀 :: [#150] DesignSystem DetailView 추가

- App/Sources/Application/NeedleGenerated.swift
- App/Sources/Feature/InputPostFeature/Source/InputPostComponent.swift
- App/Sources/Feature/InputPostFeature/Source/InputPostView.swift
- App/Sources/Feature/InputPostFeature/Source/InputPostViewModel.swift
- Service/Sources/Domain/PostDomain/DTO/Request/InputPostRequestDTO.swift
게시글 추가 API 연결
게시글 추가 기능을 추가했어요.
> 🔀 :: 게시글 - 게시글 추가 API연결

- App/Sources/Application/DI/AppComponent.swift
- App/Sources/Application/NeedleGenerated.swift
- App/Sources/Feature/ClubDetailFaeture/Interface/ClubDetailFactory.swift
- App/Sources/Feature/ClubDetailFaeture/Source/ClubDetailComponent.swift
- App/Sources/Feature/ClubDetailFaeture/Source/ClubDetailView.swift
- App/Sources/Feature/ClubDetailFaeture/Source/ClubDetailViewModel.swift
- App/Sources/Feature/ClubListFeature/Source/ClubListComponent.swift
- App/Sources/Feature/ClubListFeature/Source/ClubListView.swift
- App/Sources/Feature/ClubListFeature/Source/ClubListViewModel.swift
- App/Sources/Feature/ClubListFeature/Source/Component/ClubListEmptyContentView.swift
- App/Sources/Feature/ClubListFeature/Source/Component/ClubListRow.swift
- Service/Sources/Data/DataSource/Club/RemoteClubDataSourceImpl.swift
- Service/Sources/Data/Repository/Club/ClubRepositoryImpl.swift
- Service/Sources/Data/UseCase/Club/QueryClubDatailUseCaseImpl.swift
- Service/Sources/Data/UseCase/Club/QueryClubListUseCaseImpl.swift
- Service/Sources/Data/UseCase/Club/QueryStudentDetailByClubUseCaseImpl.swift
- Service/Sources/Domain/ClubDomain/API/ClubAPI.swift
- Service/Sources/Domain/ClubDomain/DTO/Response/ClubDetailResponseDTO.swift
- Service/Sources/Domain/ClubDomain/DTO/Response/ClubListResponseDTO.swift
- Service/Sources/Domain/ClubDomain/DataSource/RemoteClubDataSource.swift
- Service/Sources/Domain/ClubDomain/Entity/ClubDetailEntity.swift
- Service/Sources/Domain/ClubDomain/Entity/ClubEntity.swift
- Service/Sources/Domain/ClubDomain/Repository/ClubRepository.swift
- Service/Sources/Domain/ClubDomain/UseCase/QueryClubDetailUseCase.swift
- Service/Sources/Domain/ClubDomain/UseCase/QueryClubListUseCase.swift
- Service/Sources/Domain/ClubDomain/UseCase/QueryStudentDetailByClubUseCase.swift
- Service/Sources/Testing/UseCase/QueryClubDetailUseCaseStub.swift
- Service/Sources/Testing/UseCase/QueryStudentListByClubUseCaseStub.swift
동아리 목록 페이지 API 연결
동아리 목록 페이지에 API를 연결 했어요.
clubID type이 String에서 Int로 바뀌었어요.
>  🔀 :: [#178] 동아리 목록 페이지 API 연결

- App/Sources/Application/DI/AppComponent.swift
- App/Sources/Application/DI/Lecture/AppComponent+Lecture.swift
- App/Sources/Application/NeedleGenerated.swift
- App/Sources/DesignSystem/View/DetailView.swift
- App/Sources/Feature/EditPostFeature/Source/EditPostComponent.swift
- App/Sources/Feature/EditPostFeature/Source/EditPostView.swift
- App/Sources/Feature/EditPostFeature/Source/EditPostViewModel.swift
- App/Sources/Feature/InputPostFeature/Source/InputPostComponent.swift
- App/Sources/Feature/InputPostFeature/Source/InputPostView.swift
- App/Sources/Feature/InputPostFeature/Source/InputPostViewModel.swift
- App/Sources/Feature/PostDetailFeature/Source/PostDetailComponent.swift
- App/Sources/Feature/PostDetailFeature/Source/PostDetailView.swift
- App/Sources/Feature/PostDetailFeature/Source/PostDetailViewModel.swift
- App/Sources/Feature/PostDetailSettingFeature/Source/PostDetailSettingView.swift
- App/Sources/Feature/PostDetailSettingFeature/Source/PostDetailSettingViewModel.swift
- App/Sources/Feature/PostListFeature/Sources/PostListView.swift
- App/Sources/Feature/PostListFeature/Sources/PostListViewModel.swift
- Service/Sources/Data/DataSource/Post/RemotePostDataSourceImpl.swift
- Service/Sources/Data/Repository/Post/PostRepositoryImpl.swift
- Service/Sources/Data/UseCase/Post/UpdatePostUseCaseImpl.swift
- Service/Sources/Domain/PostDomain/API/PostAPI.swift
- Service/Sources/Domain/PostDomain/DTO/Request/UpdatePostRequestDTO.swift
- Service/Sources/Domain/PostDomain/DTO/Response/PostDetailResponseDTO.swift
- Service/Sources/Domain/PostDomain/DataSource/RemotePostDataSource.swift
- Service/Sources/Domain/PostDomain/Entity/PostDetailEntity.swift
- Service/Sources/Domain/PostDomain/Repository/PostRepository.swift
- Service/Sources/Domain/PostDomain/UseCase/UpdatePostUseCase.swift
게시글 수정 페이지 API 연결
게시글 수정 기능을 추가했어요.
UpdatePostRequestDTO를 추가했어요.
> 🔀 :: 게시글 수정 페이지 API 연결

- App/Sources/Application/NeedleGenerated.swift
- App/Sources/Feature/CertificationListFeature/Source/CertificationListView.swift
- App/Sources/Feature/CertificationListFeature/Source/CertificationListViewModel.swift
- App/Sources/Feature/InputCertificationFeature/Interface/InputCertificationFactory.swift
- App/Sources/Feature/InputCertificationFeature/Source/InputCertificationComponent.swift
- App/Sources/Feature/InputCertificationFeature/Source/InputCertificationView.swift
- App/Sources/Feature/InputCertificationFeature/Source/InputCertificationViewModel.swift
- Service/Sources/Domain/CertificationDomain/DTO/Request/InputCertificationRequestDTO.swift
자격증 등록 페이지에 API를 연결했어요.
자격증 등록 기능을 추가했어요.
자격증 수정 기능을 추가했어요.
> 🔀 :: 자격증 - 자격증 등록 페이지 API 연결

- App/Sources/Feature/InquiryListFeature/Source/InquiryListView.swift
> 🔀 :: [#205] 문의사항 리스트 페이지 퍼블리싱

- App/Sources/Application/DI/Admin/AppComponent+Admin.swift
- App/Sources/Application/NeedleGenerated.swift
- Service/Sources/Data/DataSource/Admin/RemoteAdminDataSourceImpl.swift
- Service/Sources/Data/Repository/Admin/AdminRespositoryImpl.swift
- Service/Sources/Data/UseCase/Admin/ApproveUserSignupUseCaseImpl.swift
- Service/Sources/Data/UseCase/Admin/FetchUserDetailUseCaseImpl.swift
- Service/Sources/Data/UseCase/Admin/FetchUserListUseCaseImpl.swift
- Service/Sources/Data/UseCase/Admin/RejectUserSignupUseCaseImpl.swift
- Service/Sources/Data/UseCase/Admin/WithdrawUserUseCaseImpl.swift
- Service/Sources/Domain/AdminDomain/API/AdminAPI.swift
- Service/Sources/Domain/AdminDomain/DTO/Response/UserDetailInfoResponseDTO.swift
- Service/Sources/Domain/AdminDomain/DTO/Response/UserInfoResponseDTO.swift
- Service/Sources/Domain/AdminDomain/DataSource/RemoteAdminDataSource.swift
- Service/Sources/Domain/AdminDomain/Entity/UserInfoEntity.swift
- Service/Sources/Domain/AdminDomain/Error/AdminDomainError.swift
- Service/Sources/Domain/AdminDomain/Repository/AdminRepository.swift
- Service/Sources/Domain/AdminDomain/UseCase/ApproveUserSignupUseCase.swift
- Service/Sources/Domain/AdminDomain/UseCase/FetchUserDetailUseCase.swift
- Service/Sources/Domain/AdminDomain/UseCase/FetchUserListUseCase.swift
- Service/Sources/Domain/AdminDomain/UseCase/RejectUserSignupUseCase.swift
- Service/Sources/Domain/AdminDomain/UseCase/WithdrawUserSignupUseCase.swift
admin 도메인을 세팅했어요.
admin 도메인을 세팅했어요.
> 🔀 :: [#207] admin 도메인 세팅

- App/Sources/Application/NeedleGenerated.swift
- App/Sources/Feature/InputInquiryFeature/Source/InputInquiryComponent.swift
- App/Sources/Feature/InputInquiryFeature/Source/InputInquiryView.swift
- App/Sources/Feature/InputInquiryFeature/Source/InputInquiryViewModel.swift
문의사항 추가 페이지에 API를 연결했어요.
문의사항 작성 기능을 추가했어요.
내가 작성한 문의사항 수정하기 기능을 추가했어요.
수정할 때 내가 작성한 문의 사항이 보일 수 있도록 문의사항을 가져오는 onAppear함수를 추가했어요.
> 🔀 :: [#212] 문의사항 추가 페이지 API연결

- App/Sources/Feature/ActivityDetailFeature/Sources/ActivityDetailView.swift
- App/Sources/Feature/ActivityDetailSettingFeature/Sources/ActivityDetailSettingView.swift
- App/Sources/Feature/ActivityListFeature/ActivityListView.swift
- App/Sources/Feature/CertificationListFeature/Source/Component/CertificationListRow.swift
- App/Sources/Feature/ClubDetailFaeture/Source/ClubDetailView.swift
- App/Sources/Feature/ClubListFeature/Source/ClubListView.swift
- App/Sources/Feature/EditPostFeature/Source/EditPostView.swift
- App/Sources/Feature/InputActivityFeature/Source/InputActivityView.swift
- App/Sources/Feature/InputCertificationFeature/Source/InputCertificationView.swift
- App/Sources/Feature/InputInquiryFeature/Source/InputInquiryView.swift
- App/Sources/Feature/InputNoticeFeature/Source/InputNoticeView.swift
- App/Sources/Feature/InputPostFeature/Source/InputPostView.swift
- App/Sources/Feature/InquiryDetailFeature/Source/InquiryDetailView.swift
- App/Sources/Feature/InquiryListFeature/Source/InquiryListView.swift
- App/Sources/Feature/LectureListDetailFeature/LectureListDetailView.swift
- App/Sources/Feature/NoticeDetailFeature/Source/NoticeDetailView.swift
- App/Sources/Feature/NoticeDetailSettingFeature/Source/NoticeDetailSettingView.swift
- App/Sources/Feature/NoticeListFeature/Source/NoticeListView.swift
- App/Sources/Feature/PostDetailFeature/Source/PostDetailView.swift
- App/Sources/Feature/PostDetailSettingFeature/Source/PostDetailSettingView.swift
- App/Sources/Feature/PostListFeature/Sources/PostListView.swift
- Service/Sources/Domain/CertificationDomain/DTO/Response/CertificationListResponseDTO.swift
- Service/Sources/Domain/CertificationDomain/Entity/CertificationInfoEntity.swift
현재 페이지의 appear함수가 실행되고 이전 페이지의 disappear 함수가 실행되면서 tabbarHidden이 제 역할을 하지 못하는 현상이 있었어요.
disappear에 조건을 달아 해결했어요.
> 🔀 :: [#219] 탭 바가 필요없는 View에 탭 바가 생성되는 현상 해결

- App/Sources/Application/DI/FAQ/AppComponent+FAQ.swift
- Service/Sources/Data/DataSource/FAQ/RemoteFAQDataSourceImpl.swift
- Service/Sources/Data/Repository/FAQ/FAQRepositoryImpl.swift
- Service/Sources/Data/UseCase/FAQ/FetchFAQDetailUseCaseImpl.swift
- Service/Sources/Data/UseCase/FAQ/FetchFAQListUseCaseImpl.swift
- Service/Sources/Data/UseCase/FAQ/InputFAQUseCaseImpl.swift
- Service/Sources/Domain/FAQDomain/API/FAQAPI.swift
- Service/Sources/Domain/FAQDomain/DTO/Request/InputFAQRequestDTO.swift
- Service/Sources/Domain/FAQDomain/DTO/Request/InputQuestionRequestDTO.swift
- Service/Sources/Domain/FAQDomain/DTO/Response/FetchFAQDetailResponseDTO.swift
- Service/Sources/Domain/FAQDomain/DTO/Response/FetchFAQListResponseDTO.swift
- Service/Sources/Domain/FAQDomain/DataSource/RemoteFAQDataSource.swift
- Service/Sources/Domain/FAQDomain/Entity/FAQDetailInfoEntity.swift
- Service/Sources/Domain/FAQDomain/Entity/FAQInfoEntity.swift
- Service/Sources/Domain/FAQDomain/Error/FAQDomainError.swift
- Service/Sources/Domain/FAQDomain/Repository/FAQRepository.swift
- Service/Sources/Domain/FAQDomain/UseCase/FetchFAQDetailUseCase.swift
- Service/Sources/Domain/FAQDomain/UseCase/FetchFAQListUseCase.swift
- Service/Sources/Domain/FAQDomain/UseCase/InputFAQUseCase.swift
> 🔀 :: [#221] FAQ 도메인 세팅

- App/Sources/Application/DI/Withdraw/AppComponent+Withdraw.swift
- App/Sources/Application/NeedleGenerated.swift
- Service/Sources/Data/DataSource/Withdraw/RemoteWithdrawDataSourceImpl.swift
- Service/Sources/Data/Repository/Withdraw/WithdrawRepositoryImpl.swift
- Service/Sources/Data/UseCase/Withdraw/FetchWithdrawUserListUseCaseImpl.swift
- Service/Sources/Domain/WithdrawDomain/API/WithdrawAPI.swift
- Service/Sources/Domain/WithdrawDomain/DTO/Response/FetchWithdrawUserListResponseDTO.swift
- Service/Sources/Domain/WithdrawDomain/DataSource/RemoteWithdrawDataSource.swift
- Service/Sources/Domain/WithdrawDomain/Entity/WithdrawUserInfoEntity.swift
- Service/Sources/Domain/WithdrawDomain/Error/WithdrawDomainError.swift
- Service/Sources/Domain/WithdrawDomain/Repository/WithdrawRepository.swift
- Service/Sources/Domain/WithdrawDomain/UseCase/FetchWithdrawUserListUseCase.swift
withdraw 도메인 세팅
withdraw 도메인을 세팅했어요.
> 🔀 :: [#223] withdraw 도메인 세팅

- App/Sources/Application/DI/AppComponent.swift
- App/Sources/Application/NeedleGenerated.swift
- App/Sources/Feature/InquiryDetailFeature/Source/InquiryDetailComponent.swift
- App/Sources/Feature/InquiryDetailFeature/Source/InquiryDetailView.swift
- App/Sources/Feature/InquiryDetailFeature/Source/InquiryDetailViewModel.swift
- App/Sources/Feature/InquiryListFeature/Source/InquiryListView.swift
- App/Sources/Feature/WriteInquiryAnswerFeature /Interface/WriteInquiryAnswerFactory.swift
- App/Sources/Feature/WriteInquiryAnswerFeature /Source/WriteInquiryAnswerComponent.swift
- App/Sources/Feature/WriteInquiryAnswerFeature /Source/WriteInquiryAnswerView.swift
- App/Sources/Feature/WriteInquiryAnswerFeature /Source/WriteInquiryAnswerViewModel.swift
> 🔀 :: [#231] 문의사항 답변 작성 페이지 퍼블리싱

- App/Sources/Application/NeedleGenerated.swift
- App/Sources/Feature/ChangePasswordFeature/Source/ChangePasswordComponent.swift
- App/Sources/Feature/ChangePasswordFeature/Source/ChangePasswordView.swift
- App/Sources/Feature/ChangePasswordFeature/Source/ChangePasswordViewModel.swift
비밀번호 변경 페이지 API 연결
비밀번호 변경 기능을 추가했어요.
> 🔀 :: [#241] 비밀번호 변경 페이지 API 연결

- App/Sources/Application/DI/AppComponent.swift
- App/Sources/Application/NeedleGenerated.swift
- App/Sources/DesignSystem/TextField/SecureBitgoeulTextField.swift
- App/Sources/Feature/FindPasswordFeature/Interface/FindPasswordFactory.swift
- App/Sources/Feature/FindPasswordFeature/Source/FindPasswordComponent.swift
- App/Sources/Feature/FindPasswordFeature/Source/FindPasswordView.swift
- App/Sources/Feature/FindPasswordFeature/Source/FindPasswordViewModel.swift
- App/Sources/Feature/FindPasswordFeature/Source/View/SendEmailView.swift
- App/Sources/Feature/LoginFeature/Sources/LoginComponent.swift
- App/Sources/Feature/LoginFeature/Sources/LoginView.swift
- App/Sources/Feature/LoginFeature/Sources/LoginViewModel.swift
비밀번호 찾기 이메일 인증 전송, 이메일 전송 완료 페이지를 퍼블리싱했어요.
https://github.com/GSM-MSG/Bitgouel-iOS/assets/105629604/e31e750b-09eb-4332-8e31-d8d525079879
> 🔀 :: [#252] 비밀번호 찾기 - 이메일 인증페이지 퍼블리싱

- App/Sources/Application/DI/Auth/AppComponent+Auth.swift
- App/Sources/Application/NeedleGenerated.swift
- App/Sources/Feature/FindPasswordFeature/Source/FindPasswordComponent.swift
- App/Sources/Feature/FindPasswordFeature/Source/FindPasswordView.swift
- App/Sources/Feature/FindPasswordFeature/Source/FindPasswordViewModel.swift
- Service/Sources/Data/DataSource/Auth/RemoteDataSourceImpl.swift
- Service/Sources/Data/DataSource/Email/RemoteEmailDataSourceImpl.swift
- Service/Sources/Data/Repository/Auth/AuthRepositoryImpl.swift
- Service/Sources/Data/Repository/Email/EmailRepositoryImpl.swift
- Service/Sources/Data/UseCase/Auth/FindPasswordUseCaseImpl.swift
- Service/Sources/Data/UseCase/Email/SendEmailCertificationLinkUseCaseImpl.swift
- Service/Sources/Domain/AuthDomain/API/AuthAPI.swift
- Service/Sources/Domain/AuthDomain/DataSource/RemoteAuthDataSource.swift
- Service/Sources/Domain/AuthDomain/Repository/AuthRepository.swift
- Service/Sources/Domain/AuthDomain/UseCase/FindPasswordUseCase.swift
- Service/Sources/Domain/EmailDomain/API/EmailAPI.swift
- Service/Sources/Domain/EmailDomain/DTO/EmailRequestDTO.swift
- Service/Sources/Domain/EmailDomain/DataSource/RemoteEmailDataSource.swift
- Service/Sources/Domain/EmailDomain/Repository/EmailRepository.swift
- Service/Sources/Domain/EmailDomain/UseCase/SendEmailCertificationLinkUseCase.swift
비밀번호 찾기 - 이메일 인증 페이지 API 연결
이메일 인증링크 전송 기능을 추가했어요.
> 🔀 :: [#252] 비밀번호 찾기 - 이메일 인증 페이지 API 연결

- App/Sources/Application/NeedleGenerated.swift
- App/Sources/Feature/FindPasswordFeature/Source/FindPasswordView.swift
- App/Sources/Feature/NewPasswordFeature/Interface/NewPasswordFactory.swift
- App/Sources/Feature/NewPasswordFeature/Source/NewPasswordComponent.swift
- App/Sources/Feature/NewPasswordFeature/Source/NewPasswordView.swift
- App/Sources/Feature/NewPasswordFeature/Source/NewPasswordViewModel.swift
- Service/Sources/Data/DataSource/Auth/RemoteDataSourceImpl.swift
- Service/Sources/Data/Repository/Auth/AuthRepositoryImpl.swift
- Service/Sources/Data/UseCase/Auth/FindPasswordUseCaseImpl.swift
- Service/Sources/Domain/AuthDomain/API/AuthAPI.swift
- Service/Sources/Domain/AuthDomain/DTO/Request/FindPasswordRequestDTO.swift
- Service/Sources/Domain/AuthDomain/DataSource/RemoteAuthDataSource.swift
- Service/Sources/Domain/AuthDomain/Repository/AuthRepository.swift
- Service/Sources/Domain/AuthDomain/UseCase/FindPasswordUseCase.swift
비밀번호 찾기 - 비밀변호 변경 기능 추가
비밀번호 변경 기능을 추가했어요.
task에 body로 설정하면 안 보내지는 오류가 있어서 RequestDTO로 변경해서 request를 보내도록 수정했어요.
> 🔀 :: [#252] 비밀번호 찾기 - 비밀변호 변경 기능 추가

- App/Sources/Application/NeedleGenerated.swift
- App/Sources/Feature/ActivityListFeature/Source/ActivityListView.swift
- App/Sources/Feature/ActivityListFeature/Source/ActivityListViewModel.swift
- App/Sources/Feature/ClubDetailFaeture/Source/ClubDetailViewModel.swift
- App/Sources/Feature/InquiryListFeature/Source/InquiryListView.swift
- App/Sources/Feature/InquiryListFeature/Source/InquiryListViewModel.swift
- App/Sources/Feature/LectureListFeature/Source/LectureListView.swift
- App/Sources/Feature/LectureListFeature/Source/LectureListViewModel.swift
- App/Sources/Feature/NoticeListFeature/Source/NoticeListView.swift
- App/Sources/Feature/PostListFeature/Sources/PostListView.swift
- App/Sources/Feature/PostListFeature/Sources/PostListViewModel.swift
onAppear함수 실행 후 서버에서 받는 리스트가 없을 때 없다고 보여주는 View가 없었어요
Resolves: #283 
- 학생활동 목록
- 문의사항 목록
- 공지사항 목록
- 게시글 목록
- 강의 목록
위 페이지에 
onAppear함수가 실행 중일때 로딩 뷰가 보여지도록 ProgressView를 추가했어요.
서버에서 주는 response값이 비어있을 때 결과가 없다고 보여주는 NoInfoView를 추가했어요.
> 🔀 :: [#283] 검색 결과가 없을 때 NoInfoView 띄우기

- App/Sources/Application/DI/Lecture/AppComponent+Lecture.swift
- App/Sources/Application/NeedleGenerated.swift
- App/Sources/Feature/ActivityListFeature/Source/ActivityListViewModel.swift
- App/Sources/Feature/LectureDetailSettingFeature/Sources/Component/BottomSheet/DivisionBottomSheet.swift
- App/Sources/Feature/LectureDetailSettingFeature/Sources/LectureDetailSettingComponent.swift
- App/Sources/Feature/LectureDetailSettingFeature/Sources/LectureDetailSettingView.swift
- App/Sources/Feature/LectureDetailSettingFeature/Sources/LectureDetailSettingViewModel.swift
- App/Sources/Feature/LectureListFeature/Source/LectureListView.swift
- App/Sources/Feature/LectureOpenApplyFeature/Sources/OpenLectureApplyView.swift
- App/Sources/Feature/LectureOpenApplyFeature/Sources/OpenLectureApplyViewModel.swift
- Service/Sources/Data/DataSource/Lecture/RemoteLectureDataSourceImpl.swift
- Service/Sources/Data/Repository/Lecture/LectureRepositoryImpl.swift
- Service/Sources/Data/UseCase/Lecture/FetchDivisionListUseCaseImpl.swift
- Service/Sources/Domain/LectureDomain/API/LectureAPI.swift
- Service/Sources/Domain/LectureDomain/DTO/Response/FetchDivisionListResponseDTO.swift
- Service/Sources/Domain/LectureDomain/DataSource/RemoteLectureDataSource.swift
- Service/Sources/Domain/LectureDomain/Repository/LectureRepository.swift
- Service/Sources/Domain/LectureDomain/UseCase/FetchDivisionListUseCase.swift
강의 구분 검색 기능이 추가되어서 기능을 추가했어요.
Resolves: #293 
- 강의 구분 검색 기능을 추가했어요. 
- 강의 개설 권한이 Admin -> Admin, Professor, CompanyInstructor, Government 로 변경되었어요.
- 강의 개설 실패시 에러처리가 없어서 Toast를 띄우도록 변경했어요.
> 🔀 [#293] 강의 구분 검색 기능 추가

- App/Sources/Application/DI/Lecture/AppComponent+Lecture.swift
- App/Sources/Application/NeedleGenerated.swift
- App/Sources/Feature/LectureDetailSettingFeature/Sources/LectureDetailSettingViewModel.swift
- App/Sources/Feature/StudentInfoFeature/Source/Component/AppliedLectureListRow.swift
- App/Sources/Feature/StudentInfoFeature/Source/StudentInfoComponent.swift
- App/Sources/Feature/StudentInfoFeature/Source/StudentInfoView.swift
- App/Sources/Feature/StudentInfoFeature/Source/StudentInfoViewModel.swift
- Service/Sources/Data/DataSource/Lecture/RemoteLectureDataSourceImpl.swift
- Service/Sources/Data/Repository/Lecture/LectureRepositoryImpl.swift
- Service/Sources/Data/UseCase/Lecture/FetchAppliedLectureListUseCaseImpl.swift
- Service/Sources/Domain/LectureDomain/API/LectureAPI.swift
- Service/Sources/Domain/LectureDomain/DTO/Response/FetchAppliedLectureListResponseDTO.swift
- Service/Sources/Domain/LectureDomain/DataSource/RemoteLectureDataSource.swift
- Service/Sources/Domain/LectureDomain/Entity/AppliedLectureEntity.swift
- Service/Sources/Domain/LectureDomain/Repository/LectureRepository.swift
- Service/Sources/Domain/LectureDomain/UseCase/FetchAppliedLectureListUseCase.swift
수강신청한 강의 리스트 조회 기능 추가
Resolves: #295 
수강신청한 강의 리스트 조회 기능을 추가했어요.
> 🔀 :: [#295] 수강신청한 강의 리스트 조회 기능 추가

- App/Sources/DesignSystem/View/InputFormView.swift
- App/Sources/Feature/ActivityDetailSettingFeature/Sources/ActivityDetailSettingView.swift
- App/Sources/Feature/InputActivityFeature/Source/InputActivityView.swift
- App/Sources/Feature/InputInquiryFeature/Source/InputInquiryView.swift
- App/Sources/Feature/InputNoticeFeature/Source/InputNoticeView.swift
- App/Sources/Feature/InputPostFeature/Source/InputPostView.swift
- App/Sources/Feature/LectureOpenApplyFeature/Sources/OpenLectureApplyView.swift
InputFormView, 문의사항, 게시글, 공지사항 View들에 큰 ScrollView로 감싸져 있는 부분이 어색하다고 해서 삭제했어요.
Resolves: #301 
- InputFormView, 문의사항, 게시글, 공지사항 scrollView 삭제했어요.
> 🔀 :: [#301] InputFormView, 문의사항, 게시글, 공지사항 scrollView 삭제

- App/Sources/Feature/LectureListFeature/Source/LectureListViewModel.swift
예전에 LectureType이 추가되었을 때 FilterView에는 LectureType이 추가되었지만 LectureType을 update하는 부분에 추가된 LectureType이 적용되지 않았었어요.
Resolves: #311 
- 추가된 LectureType의 case를 추가하여 LectureType이 제대로 update되도록 수정했어요.
> 🔀 :: [#311] LectureType 추가

- App/Sources/Feature/InputPostFeature/Source/InputPostView.swift
- App/Sources/Feature/InputPostFeature/Source/InputPostViewModel.swift
- App/Sources/Feature/PostDetailFeature/Source/PostDetailView.swift
- App/Sources/Feature/PostDetailFeature/Source/PostDetailViewModel.swift
- App/Sources/Feature/PostListFeature/Sources/PostListView.swift
- App/Sources/Feature/PostListFeature/Sources/PostListViewModel.swift
QA진행 중 게시글 작성, 리스트 조회, 상세 조회, 수정, 삭제 요청 실패 시 아무런 조치도 취해지지 않아서 불편함을 느꼈어요.
- 게시글 작성
- 게시글 리스트 조회
- 게시글 상세 조회
- 게시글 수정
- 게시글 삭제
요청 실패 시 Toast 메시지가 띄워지도록 추가했어요.
> 🔀 :: [#329] 게시글 Feature 예외 처리

- App/Sources/Application/NeedleGenerated.swift
- App/Sources/Feature/MainFeature/Source/View/FAQView.swift
- App/Support/Info.plist
앱 스토어 심사 중 가이드라인과 맞지 않다는 이유로 리젝을 당했어요. 
Resolves: #343 
- FAQ리스트 부분을 가운데 정렬로 되어있던 부분을 왼쪽 정렬로 수정했어요.
- default localization을 ko_KR로 수정했어요.
> 🔀 :: [#343] FAQ리스트 수정, default localization 수정

- .swiftlint.yml
- App/Sources/Application/DI/Company/AppComponent+Company.swift
- App/Sources/Application/NeedleGenerated.swift
- Scripts/.swiftformat
- Scripts/.swiftlint.yml
- Service/Sources/Base/BitgouelAPI.swift
- Service/Sources/Data/DataSource/Company/RemoteCompanyDataSourceImpl.swift
- Service/Sources/Data/Repository/Company/CompanyRepositoryImpl.swift
- Service/Sources/Data/UseCase/Company/CreatedCompanyUseCaseImpl.swift
- Service/Sources/Data/UseCase/Company/DeleteCompanyUseCaseImpl.swift
- Service/Sources/Data/UseCase/Company/FetchCompanyListUseCaseImpl.swift
- Service/Sources/Domain/CompanyDomain/API/CompanyAPI.swift
- Service/Sources/Domain/CompanyDomain/DTO/Request/CreatedCompanyRequestDTO.swift
- Service/Sources/Domain/CompanyDomain/DTO/Response/CompanyListResponseDTO.swift
- Service/Sources/Domain/CompanyDomain/DataSource/RemoteCompanyDataSource.swift
- Service/Sources/Domain/CompanyDomain/Entity/CompanyInfoEntity.swift
- Service/Sources/Domain/CompanyDomain/Error/CompanyDomainError.swift
- Service/Sources/Domain/CompanyDomain/Repository/CompanyRepository.swift
- Service/Sources/Domain/CompanyDomain/UseCase/CreatedCompanyUseCase.swift
- Service/Sources/Domain/CompanyDomain/UseCase/DeleteCompanyUseCase.swift
- Service/Sources/Domain/CompanyDomain/UseCase/FetchCompanyListUseCase.swift
기업 CRUD 기능이 추가되면서 CompanyDomain을 세팅합니다.
Resolves: #368 
- 기업 리스트 조회
- 기업 생성
- 기업 삭제
위의 API를 세팅했습니다.
> 🔀 :: [#368] Company 도메인 세팅

- App/Sources/Feature/AdminBaseFeature/Source/Component/View/AdminListPageRow.swift
- App/Sources/Feature/AdminBaseFeature/Source/Component/View/BottomSheet/FieldBottomSheet.swift
- App/Sources/Feature/AdminBaseFeature/Source/Component/View/InputDataView.swift
- App/Sources/Feature/CompanyListFeature/Source/CompanyListView.swift
- App/Sources/Feature/CompanyListFeature/Source/CompanyListViewModel.swift
- App/Sources/Feature/CompanyListFeature/Source/Component/OrganizationDetailBottomSheet.swift
- Service/Sources/Base/Enum/FieldType.swift
- Service/Sources/Domain/CompanyDomain/Entity/CompanyInfoEntity.swift
- Service/Sources/Domain/SchoolDoamin/DTO/Response/SchoolListResponseDTO.swift
https://github.com/user-attachments/assets/7701d241-9f90-422b-802a-c013a3b4115f
- 기업목록 페이지를 퍼블리싱 했어요.
- 테스트용 더미 데이터는 API 연동 후 삭제 할게요!!
> 🔀 :: [#380] 기업 목록 페이지 퍼블리싱

- App/Sources/Application/NeedleGenerated.swift
- App/Sources/Feature/CompanyListFeature/Source/CompanyListComponent.swift
- App/Sources/Feature/CompanyListFeature/Source/CompanyListView.swift
- App/Sources/Feature/CompanyListFeature/Source/CompanyListViewModel.swift
- App/Sources/Utils/Extensions/Error+DomainErrorMessage.swift
- Service/Sources/Data/DataSource/Company/RemoteCompanyDataSourceImpl.swift
- Service/Sources/Data/Repository/Company/CompanyRepositoryImpl.swift
- Service/Sources/Data/UseCase/Company/DeleteCompanyUseCaseImpl.swift
- Service/Sources/Domain/CompanyDomain/API/CompanyAPI.swift
- Service/Sources/Domain/CompanyDomain/DTO/Response/CompanyListResponseDTO.swift
- Service/Sources/Domain/CompanyDomain/DataSource/RemoteCompanyDataSource.swift
- Service/Sources/Domain/CompanyDomain/Entity/CompanyInfoEntity.swift
- Service/Sources/Domain/CompanyDomain/Repository/CompanyRepository.swift
- Service/Sources/Domain/CompanyDomain/UseCase/DeleteCompanyUseCase.swift
https://github.com/user-attachments/assets/a9f5e189-8844-490c-833a-ee6e0649ee40
- 기업 리스트 조회
- 기업 삭제 
위 기능을 CompanyListFeature에서 처리하도록 API를 연동했습니다.
> 🔀 :: [#380] 기업 목록 페이지 API 연결

- App/Sources/Application/BitgouelApp.swift
- App/Sources/Application/DI/AppComponent.swift
- App/Sources/Application/NeedleGenerated.swift
- App/Sources/Feature/AdminBaseFeature/Source/Component/View/BottomSheet/FieldBottomSheet.swift
- App/Sources/Feature/AdminBaseFeature/Source/Component/View/InputDataView.swift
- App/Sources/Feature/CompanyListFeature/Source/CompanyListComponent.swift
- App/Sources/Feature/CompanyListFeature/Source/CompanyListView.swift
- App/Sources/Feature/InputCompanyFeature/Interface/InputCompanyFactory.swift
- App/Sources/Feature/InputCompanyFeature/Source/InputCompanyComponent.swift
- App/Sources/Feature/InputCompanyFeature/Source/InputCompanyView.swift
- App/Sources/Feature/InputCompanyFeature/Source/InputCompanyViewModel.swift
- App/Sources/Feature/LectureDetailSettingFeature/Sources/Component/PickerTextField.swift
- Service/Sources/Domain/CompanyDomain/DTO/Request/CreatedCompanyRequestDTO.swift
https://github.com/user-attachments/assets/cdac9a30-c05b-401b-93bb-8d88d319dd9b
Resolves: #380 
- 기업 등록 페이지지를 퍼블리싱했어요
- 기업 등록 기능을 추가했어요
기업 등록 페이지가 View도 CustomView를 미리 만들어놔서 코드도 짧고 기업 등록 기능을 추가하는 것도 큰 기능이 아니기 때문에 같이 작업했어요!
> 🔀 :: [#380] 기업 등록 페이지

- App/Sources/Feature/MainFeature/Source/TabView/Club/CultureIndustryClubView.swift
메인페이지 취업동아리 소개 부분의 문화산업 Tab의 동아리들이 변경되었어요!
Resolves: #396 
변경된 동아리 이름들을 적용했어요
> [#396] 문화 산업 부분 동아리 이름 수정

- README.md
빛고을 iOS 리드미가 너무 휑해서 추가했어요.
Resolves: #410 
빛고을 iOS 리드미를 작성했어요.
> 🔀 :: [#410] 빛고을 리드미 작성
